import type {
  JobDef,
  JobId,
  MetaDef,
  MetaId,
  NodeDef,
  NodeId,
  ResourceDef,
  ResourceId,
  WorldDef,
  WorldId,
} from './types';

export const WORLDS: Record<WorldId, WorldDef> = {
  realm: {
    id: 'realm',
    name: 'Realm',
    tagline: 'Gather materials and raise buildings.',
    unlockHint: 'Open from the start.',
    startsUnlocked: true,
    headStartNodes: ['hut'],
  },
  arcana: {
    id: 'arcana',
    name: 'Arcana',
    tagline: 'Draw on Mana and discover stranger magic.',
    unlockHint: 'Grow the Realm to 10 buildings, then build a Shrine.',
    startsUnlocked: false,
    headStartNodes: ['manaWell'],
  },
  lab: {
    id: 'lab',
    name: 'Lab',
    tagline: 'Fund scholars and push the tech tree.',
    unlockHint: 'Grow the Realm to 10 buildings, then build a Library.',
    startsUnlocked: false,
    headStartNodes: ['scholar'],
  },
};

export const WORLD_ORDER: WorldId[] = ['realm', 'arcana', 'lab'];

export const RESOURCES: Record<ResourceId, ResourceDef> = {
  wood: { id: 'wood', name: 'Wood', world: 'realm', click: 1, value: 1 },
  stone: { id: 'stone', name: 'Stone', world: 'realm', click: 1, value: 1.5 },
  iron: { id: 'iron', name: 'Iron', world: 'realm', value: 6, revealedBy: 'mine' },
  mana: { id: 'mana', name: 'Mana', world: 'arcana', click: 1, value: 1.5 },
  essence: { id: 'essence', name: 'Essence', world: 'arcana', value: 15, revealedBy: 'condenser' },
  aether: { id: 'aether', name: 'Aether', world: 'arcana', value: 120, revealedBy: 'aetherRift' },
  research: { id: 'research', name: 'Research', world: 'lab', click: 1, value: 2 },
};

/** Realm population rules. */
export const POPULATION = {
  /** People at the start of every Realm run. */
  start: 2,
  /** Housing available before any Huts. */
  baseHousing: 3,
  /** People arrive at this fraction of the housing cap per second, but never slower than `minArrival`. */
  arrivalPerHousing: 0.02,
  minArrival: 0.1,
};

const jobList: JobDef[] = [
  { id: 'woodcutter', name: 'Woodcutters', resource: 'wood', baseYield: 0.5 },
  { id: 'stonecutter', name: 'Stonecutters', resource: 'stone', baseYield: 0.4 },
  {
    id: 'miner',
    name: 'Miners',
    resource: 'iron',
    baseYield: 0.2,
    requires: ['mine'],
    effects: [{ stat: 'rate:mana', kind: 'mul', amount: 0.98 }],
  },
];

export const JOBS = Object.fromEntries(jobList.map((j) => [j.id, j])) as Record<JobId, JobDef>;
export const JOB_ORDER: JobId[] = jobList.map((j) => j.id);

export const RESOURCE_ORDER: ResourceId[] = ['wood', 'stone', 'iron', 'mana', 'essence', 'aether', 'research'];

const nodeList: NodeDef[] = [
  // ---------------------------------------------------------------- Realm
  {
    id: 'hut',
    world: 'realm',
    kind: 'building',
    name: 'Hut',
    description: 'Room for more people to move in.',
    baseCost: { wood: 15 },
    costGrowth: 1.4,
    effects: [{ stat: 'housing', kind: 'add', amount: 2 }],
  },
  {
    id: 'lumberCamp',
    world: 'realm',
    kind: 'building',
    name: 'Lumber Camp',
    description: 'Saws and sledges for your woodcutters.',
    baseCost: { wood: 25 },
    costGrowth: 1.3,
    effects: [{ stat: 'yield:wood', kind: 'add', amount: 0.2 }],
  },
  {
    id: 'quarry',
    world: 'realm',
    kind: 'building',
    name: 'Quarry',
    description: 'A proper pit for your stonecutters.',
    baseCost: { wood: 35 },
    costGrowth: 1.3,
    effects: [{ stat: 'yield:stone', kind: 'add', amount: 0.15 }],
  },
  {
    id: 'workshop',
    world: 'realm',
    kind: 'building',
    name: 'Workshop',
    description: 'Better tools for every worker.',
    baseCost: { wood: 40, stone: 25 },
    costGrowth: 2.5,
    maxLevel: 10,
    requires: ['lumberCamp', 'quarry'],
    effects: [
      { stat: 'rate:wood', kind: 'mul', amount: 1.15 },
      { stat: 'rate:stone', kind: 'mul', amount: 1.15 },
      { stat: 'rate:iron', kind: 'mul', amount: 1.15 },
      { stat: 'click:wood', kind: 'add', amount: 1 },
      { stat: 'click:stone', kind: 'add', amount: 1 },
    ],
  },
  {
    id: 'mine',
    world: 'realm',
    kind: 'building',
    name: 'Mine',
    description: 'Opens the Miner job, and each Mine makes miners dig faster. Miners disturb the ley lines.',
    baseCost: { wood: 60, stone: 80 },
    costGrowth: 1.35,
    requires: ['quarry'],
    effects: [{ stat: 'yield:iron', kind: 'add', amount: 0.05 }],
  },
  {
    id: 'foundry',
    world: 'realm',
    kind: 'building',
    name: 'Foundry',
    description: 'Iron machinery speeds up the whole Realm.',
    baseCost: { stone: 200, iron: 40 },
    costGrowth: 3,
    maxLevel: 10,
    requires: ['mine'],
    effects: [{ stat: 'prod:realm', kind: 'mul', amount: 1.2 }],
  },
  {
    id: 'library',
    world: 'realm',
    kind: 'building',
    name: 'Library',
    description: 'A place to study. The first one opens the Lab.',
    baseCost: { wood: 150, stone: 100 },
    costGrowth: 1.25,
    requires: ['workshop'],
    requiresBuildings: 10,
    unlocksWorld: 'lab',
    effects: [{ stat: 'rate:research', kind: 'add', amount: 0.5 }],
  },
  {
    id: 'shrine',
    world: 'realm',
    kind: 'building',
    name: 'Shrine',
    description: 'A quiet stone circle. The first one opens Arcana.',
    baseCost: { wood: 120, stone: 150 },
    costGrowth: 1.3,
    requires: ['workshop'],
    requiresBuildings: 10,
    unlocksWorld: 'arcana',
    effects: [{ stat: 'rate:mana', kind: 'add', amount: 0.3 }],
  },

  // --------------------------------------------------------------- Arcana
  {
    id: 'manaWell',
    world: 'arcana',
    kind: 'building',
    name: 'Mana Well',
    description: 'Draws Mana up from below.',
    baseCost: { mana: 10 },
    costGrowth: 1.15,
    effects: [{ stat: 'rate:mana', kind: 'add', amount: 0.4 }],
  },
  {
    id: 'condenser',
    world: 'arcana',
    kind: 'building',
    name: 'Condenser',
    description: 'Presses Mana into Essence. Burns 1 Mana/s each.',
    baseCost: { mana: 50 },
    costGrowth: 1.2,
    requires: ['manaWell'],
    upkeep: { mana: 1 },
    effects: [{ stat: 'rate:essence', kind: 'add', amount: 0.1 }],
  },
  {
    id: 'focusCrystal',
    world: 'arcana',
    kind: 'building',
    name: 'Focus Crystal',
    description: 'Focuses the flow of Mana.',
    baseCost: { mana: 100, essence: 10 },
    costGrowth: 2.5,
    maxLevel: 10,
    requires: ['condenser'],
    effects: [
      { stat: 'rate:mana', kind: 'mul', amount: 1.25 },
      { stat: 'click:mana', kind: 'mul', amount: 1.5 },
    ],
  },
  {
    id: 'enchantedTools',
    world: 'arcana',
    kind: 'building',
    name: 'Enchanted Tools',
    description: 'Tools that work a little by themselves.',
    baseCost: { essence: 25 },
    costGrowth: 3,
    maxLevel: 5,
    requires: ['condenser'],
    effects: [{ stat: 'prod:realm', kind: 'mul', amount: 1.25 }],
  },
  {
    id: 'aetherRift',
    world: 'arcana',
    kind: 'building',
    name: 'Aether Rift',
    description: 'Tears reality open to let Aether through. Feeds on 0.5 Essence/s each, and the tear confuses instruments.',
    baseCost: { mana: 500, essence: 100 },
    costGrowth: 2,
    requires: ['condenser'],
    upkeep: { essence: 0.5 },
    effects: [
      { stat: 'rate:aether', kind: 'add', amount: 0.05 },
      { stat: 'rate:research', kind: 'mul', amount: 0.85 },
    ],
  },
  {
    id: 'aetherLens',
    world: 'arcana',
    kind: 'building',
    name: 'Aether Lens',
    description: 'Aether bends every spell into something stronger.',
    baseCost: { aether: 5 },
    costGrowth: 3,
    maxLevel: 5,
    requires: ['aetherRift'],
    effects: [{ stat: 'prod:arcana', kind: 'mul', amount: 1.5 }],
  },

  // ------------------------------------------------------------------ Lab
  {
    id: 'scholar',
    world: 'lab',
    kind: 'building',
    name: 'Scholar',
    description: 'Produces Research.',
    baseCost: { research: 10 },
    costGrowth: 1.15,
    effects: [{ stat: 'rate:research', kind: 'add', amount: 0.3 }],
  },
  {
    id: 'laboratory',
    world: 'lab',
    kind: 'building',
    name: 'Laboratory',
    description: 'Iron equipment for serious experiments.',
    baseCost: { research: 60, iron: 20 },
    costGrowth: 1.25,
    requires: ['scholar'],
    effects: [{ stat: 'rate:research', kind: 'add', amount: 1.5 }],
  },
  {
    id: 'scientificMethod',
    world: 'lab',
    kind: 'tech',
    name: 'Scientific Method',
    description: 'Research is done properly now.',
    baseCost: { research: 50 },
    costGrowth: 1,
    effects: [{ stat: 'rate:research', kind: 'mul', amount: 1.25 }],
  },
  {
    id: 'metallurgy',
    world: 'lab',
    kind: 'tech',
    name: 'Metallurgy',
    description: 'Better smelting in the Realm.',
    baseCost: { research: 150 },
    costGrowth: 1,
    requires: ['scientificMethod'],
    effects: [{ stat: 'rate:iron', kind: 'mul', amount: 1.5 }],
  },
  {
    id: 'rationalism',
    world: 'lab',
    kind: 'tech',
    name: 'Rationalism',
    description: 'Faster research. Widespread disbelief weakens magic.',
    baseCost: { research: 300 },
    costGrowth: 1,
    requires: ['scientificMethod'],
    effects: [
      { stat: 'rate:research', kind: 'mul', amount: 1.3 },
      { stat: 'rate:mana', kind: 'mul', amount: 0.8 },
    ],
  },
  {
    id: 'arcaneTheory',
    world: 'lab',
    kind: 'tech',
    name: 'Arcane Theory',
    description: 'Studying magic instead of dismissing it.',
    baseCost: { research: 400, essence: 30 },
    costGrowth: 1,
    requires: ['scientificMethod'],
    effects: [{ stat: 'rate:essence', kind: 'mul', amount: 1.3 }],
  },
  {
    id: 'industrialization',
    world: 'lab',
    kind: 'tech',
    name: 'Industrialization',
    description: 'Cheaper Realm buildings. The smog chokes Essence.',
    baseCost: { research: 600, iron: 100 },
    costGrowth: 1,
    requires: ['metallurgy'],
    effects: [
      { stat: 'cost:realm', kind: 'mul', amount: 0.85 },
      { stat: 'rate:essence', kind: 'mul', amount: 0.85 },
    ],
  },
  {
    id: 'automation',
    world: 'lab',
    kind: 'tech',
    name: 'Automation',
    description: 'Machines take over the Realm\'s busywork.',
    baseCost: { research: 1500, iron: 200 },
    costGrowth: 1,
    requires: ['industrialization'],
    effects: [{ stat: 'prod:realm', kind: 'mul', amount: 1.5 }],
  },
  {
    id: 'thaumicPhysics',
    world: 'lab',
    kind: 'tech',
    name: 'Thaumic Physics',
    description: 'Science and magic agree on something at last.',
    baseCost: { research: 2000, aether: 5 },
    costGrowth: 1,
    requires: ['rationalism', 'arcaneTheory'],
    effects: [
      { stat: 'rate:aether', kind: 'mul', amount: 2 },
      { stat: 'prod:lab', kind: 'mul', amount: 1.5 },
    ],
  },
];

export const NODES = Object.fromEntries(nodeList.map((n) => [n.id, n])) as Record<NodeId, NodeDef>;
export const NODE_ORDER: NodeId[] = nodeList.map((n) => n.id);

const metaList: MetaDef[] = [
  {
    id: 'headStartRealm',
    name: 'Head Start: Realm',
    description: 'Each Realm run starts with +2 Huts.',
    baseCost: 1,
    costGrowth: 2,
    maxLevel: 5,
  },
  {
    id: 'headStartArcana',
    name: 'Head Start: Arcana',
    description: 'Each Arcana run starts with +2 Mana Wells.',
    baseCost: 1,
    costGrowth: 2,
    maxLevel: 5,
  },
  {
    id: 'headStartLab',
    name: 'Head Start: Lab',
    description: 'Each Lab run starts with +2 Scholars.',
    baseCost: 1,
    costGrowth: 2,
    maxLevel: 5,
  },
  {
    id: 'resonanceRealm',
    name: 'Resonance: Realm',
    description: 'Realm production x1.1, permanently.',
    baseCost: 2,
    costGrowth: 1.6,
    effects: [{ stat: 'prod:realm', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'resonanceArcana',
    name: 'Resonance: Arcana',
    description: 'Arcana production x1.1, permanently.',
    baseCost: 2,
    costGrowth: 1.6,
    effects: [{ stat: 'prod:arcana', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'resonanceLab',
    name: 'Resonance: Lab',
    description: 'Lab production x1.1, permanently.',
    baseCost: 2,
    costGrowth: 1.6,
    effects: [{ stat: 'prod:lab', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'dampening',
    name: 'Dampening',
    description: 'Harmful effects between worlds are 10% weaker.',
    baseCost: 3,
    costGrowth: 2,
    maxLevel: 5,
  },
  {
    id: 'amplify',
    name: 'Amplify',
    description: 'Helpful effects between worlds are 10% stronger.',
    baseCost: 3,
    costGrowth: 2,
    maxLevel: 10,
  },
  {
    id: 'attunement',
    name: 'Echo Attunement',
    description: '+10% Echoes from every reset.',
    baseCost: 5,
    costGrowth: 2,
  },
  {
    id: 'retainedKnowledge',
    name: 'Retained Knowledge',
    description: 'Lab resets keep your most expensive tech (one more per level).',
    baseCost: 5,
    costGrowth: 3,
    maxLevel: 3,
  },
];

export const META = Object.fromEntries(metaList.map((m) => [m.id, m])) as Record<MetaId, MetaDef>;
export const META_ORDER: MetaId[] = metaList.map((m) => m.id);
