import type {
  JobDef,
  JobId,
  MetaDef,
  MetaId,
  NodeDef,
  NodeId,
  ResourceDef,
  ResourceId,
  WorldDef,
  WorldId,
} from './types';

export const WORLDS: Record<WorldId, WorldDef> = {
  realm: {
    id: 'realm',
    name: 'Realm',
    tagline: 'Feed your people, put them to work, and raise buildings.',
    unlockHint: 'Open from the start.',
    startsUnlocked: true,
    headStartNodes: ['hut'],
  },
  arcana: {
    id: 'arcana',
    name: 'Arcana',
    tagline: 'Draw on Mana and discover stranger magic.',
    unlockHint: 'Grow the Realm to 10 buildings, then build a Shrine.',
    startsUnlocked: false,
    headStartNodes: ['manaWell'],
  },
  lab: {
    id: 'lab',
    name: 'Lab',
    tagline: 'Fund scholars and push the tech tree.',
    unlockHint: 'Grow the Realm to 10 buildings, then build a Library.',
    startsUnlocked: false,
    headStartNodes: ['scholar'],
  },
};

export const WORLD_ORDER: WorldId[] = ['realm', 'arcana', 'lab'];

export const RESOURCES: Record<ResourceId, ResourceDef> = {
  wood: { id: 'wood', name: 'Wood', world: 'realm', click: 1, value: 1 },
  stone: { id: 'stone', name: 'Stone', world: 'realm', click: 1, value: 1.5 },
  food: { id: 'food', name: 'Food', world: 'realm', click: 1, value: 1 },
  clay: { id: 'clay', name: 'Clay', world: 'realm', value: 2, revealedBy: 'clayPit' },
  planks: { id: 'planks', name: 'Planks', world: 'realm', value: 4, revealedBy: 'sawmill' },
  bricks: { id: 'bricks', name: 'Bricks', world: 'realm', value: 5, revealedBy: 'kiln' },
  iron: { id: 'iron', name: 'Iron', world: 'realm', value: 6, revealedBy: 'mine' },
  coal: { id: 'coal', name: 'Coal', world: 'realm', value: 5, revealedBy: 'coalMine' },
  steel: { id: 'steel', name: 'Steel', world: 'realm', value: 25, revealedBy: 'blastFurnace' },
  glass: { id: 'glass', name: 'Glass', world: 'realm', value: 20, revealedBy: 'glassworks' },
  gold: { id: 'gold', name: 'Gold', world: 'realm', value: 60, revealedBy: 'goldMine' },
  runestone: { id: 'runestone', name: 'Runestone', world: 'realm', value: 80, revealedBy: 'runesmith' },
  mana: { id: 'mana', name: 'Mana', world: 'arcana', click: 1, value: 1.5 },
  essence: { id: 'essence', name: 'Essence', world: 'arcana', value: 15, revealedBy: 'condenser' },
  aether: { id: 'aether', name: 'Aether', world: 'arcana', value: 120, revealedBy: 'aetherRift' },
  research: { id: 'research', name: 'Research', world: 'lab', click: 1, value: 2 },
};

/** Realm population rules. */
export const POPULATION = {
  /** People at the start of every Realm run. */
  start: 2,
  /** Housing available before any Huts. */
  baseHousing: 3,
  /** People per second born or arriving while there is free housing, before `growth` modifiers (1 every 20s). */
  baseGrowth: 0.05,
  /** Food eaten to bring in each new person; nobody arrives while the stores are empty. */
  foodPerPerson: 10,
};

const jobList: JobDef[] = [
  { id: 'woodcutter', name: 'Woodcutters', resource: 'wood', baseYield: 0.5 },
  { id: 'stonecutter', name: 'Stonecutters', resource: 'stone', baseYield: 0.4 },
  { id: 'farmer', name: 'Farmers', resource: 'food', baseYield: 0.6 },
  { id: 'digger', name: 'Diggers', resource: 'clay', baseYield: 0.3, requires: ['clayPit'] },
  {
    id: 'miner',
    name: 'Miners',
    resource: 'iron',
    baseYield: 0.2,
    requires: ['mine'],
    effects: [{ stat: 'rate:mana', kind: 'mul', amount: 0.98 }],
  },
  {
    id: 'collier',
    name: 'Colliers',
    resource: 'coal',
    baseYield: 0.25,
    requires: ['coalMine'],
    effects: [{ stat: 'rate:essence', kind: 'mul', amount: 0.99 }],
  },
  {
    id: 'prospector',
    name: 'Prospectors',
    resource: 'gold',
    baseYield: 0.05,
    requires: ['goldMine'],
    effects: [{ stat: 'rate:research', kind: 'mul', amount: 0.99 }],
  },
];

export const JOBS = Object.fromEntries(jobList.map((j) => [j.id, j])) as Record<JobId, JobDef>;
export const JOB_ORDER: JobId[] = jobList.map((j) => j.id);

export const RESOURCE_ORDER = Object.keys(RESOURCES) as ResourceId[];

const nodeList: NodeDef[] = [
  // ---------------------------------------------------------------- Realm
  // Basics: housing and raw materials.
  {
    id: 'hut',
    world: 'realm',
    kind: 'building',
    name: 'Hut',
    description: 'Room for more people to move in.',
    baseCost: { wood: 15 },
    costGrowth: 1.4,
    effects: [{ stat: 'housing', kind: 'add', amount: 2 }],
  },
  {
    id: 'farm',
    world: 'realm',
    kind: 'building',
    name: 'Farm',
    description: 'Fields for your farmers. New people need Food to move in.',
    baseCost: { wood: 20 },
    costGrowth: 1.3,
    effects: [{ stat: 'yield:food', kind: 'add', amount: 0.3 }],
  },
  {
    id: 'lumberCamp',
    world: 'realm',
    kind: 'building',
    name: 'Lumber Camp',
    description: 'Saws and sledges for your woodcutters.',
    baseCost: { wood: 25 },
    costGrowth: 1.3,
    effects: [{ stat: 'yield:wood', kind: 'add', amount: 0.2 }],
  },
  {
    id: 'quarry',
    world: 'realm',
    kind: 'building',
    name: 'Quarry',
    description: 'A proper pit for your stonecutters.',
    baseCost: { wood: 35 },
    costGrowth: 1.3,
    effects: [{ stat: 'yield:stone', kind: 'add', amount: 0.15 }],
  },
  {
    id: 'clayPit',
    world: 'realm',
    kind: 'building',
    name: 'Clay Pit',
    description: 'Opens the Digger job. Each pit makes diggers faster.',
    baseCost: { wood: 40, stone: 20 },
    costGrowth: 1.3,
    requires: ['quarry'],
    effects: [{ stat: 'yield:clay', kind: 'add', amount: 0.1 }],
  },
  {
    id: 'workshop',
    world: 'realm',
    kind: 'building',
    name: 'Workshop',
    description: 'Better tools for every worker.',
    baseCost: { wood: 40, stone: 25 },
    costGrowth: 2.5,
    maxLevel: 10,
    requires: ['lumberCamp', 'quarry'],
    effects: [
      { stat: 'rate:wood', kind: 'mul', amount: 1.15 },
      { stat: 'rate:stone', kind: 'mul', amount: 1.15 },
      { stat: 'rate:clay', kind: 'mul', amount: 1.15 },
      { stat: 'rate:iron', kind: 'mul', amount: 1.15 },
      { stat: 'click:wood', kind: 'add', amount: 1 },
      { stat: 'click:stone', kind: 'add', amount: 1 },
      { stat: 'click:food', kind: 'add', amount: 1 },
    ],
  },

  // Crafting: turning raw materials into better ones.
  {
    id: 'sawmill',
    world: 'realm',
    kind: 'building',
    name: 'Sawmill',
    description: 'Cuts Wood into Planks.',
    baseCost: { wood: 80, stone: 30 },
    costGrowth: 1.35,
    requires: ['workshop'],
    upkeep: { wood: 1 },
    effects: [{ stat: 'rate:planks', kind: 'add', amount: 0.4 }],
  },
  {
    id: 'kiln',
    world: 'realm',
    kind: 'building',
    name: 'Kiln',
    description: 'Fires Clay into Bricks, burning Wood.',
    baseCost: { stone: 60, clay: 40 },
    costGrowth: 1.35,
    requires: ['clayPit'],
    upkeep: { clay: 1, wood: 0.5 },
    effects: [{ stat: 'rate:bricks', kind: 'add', amount: 0.3 }],
  },
  {
    id: 'house',
    world: 'realm',
    kind: 'building',
    name: 'House',
    description: 'Proper homes with room for a family.',
    baseCost: { planks: 30, bricks: 20 },
    costGrowth: 1.35,
    requires: ['sawmill', 'kiln'],
    effects: [{ stat: 'housing', kind: 'add', amount: 5 }],
  },
  {
    id: 'mine',
    world: 'realm',
    kind: 'building',
    name: 'Mine',
    description: 'Opens the Miner job, and each Mine makes miners dig faster. Miners disturb the ley lines.',
    baseCost: { wood: 60, stone: 80 },
    costGrowth: 1.35,
    requires: ['quarry'],
    effects: [{ stat: 'yield:iron', kind: 'add', amount: 0.05 }],
  },
  {
    id: 'coalMine',
    world: 'realm',
    kind: 'building',
    name: 'Coal Mine',
    description: 'Opens the Collier job. Coal soot drifts into the magic.',
    baseCost: { planks: 60, stone: 100 },
    costGrowth: 1.35,
    requires: ['mine', 'sawmill'],
    effects: [{ stat: 'yield:coal', kind: 'add', amount: 0.05 }],
  },
  {
    id: 'foundry',
    world: 'realm',
    kind: 'building',
    name: 'Foundry',
    description: 'Iron machinery speeds up the whole Realm.',
    baseCost: { bricks: 150, iron: 40 },
    costGrowth: 3,
    maxLevel: 10,
    requires: ['mine', 'kiln'],
    effects: [{ stat: 'prod:realm', kind: 'mul', amount: 1.2 }],
  },
  {
    id: 'market',
    world: 'realm',
    kind: 'building',
    name: 'Market',
    description: 'Traders make every Realm building cheaper.',
    baseCost: { planks: 100, bricks: 60 },
    costGrowth: 1.8,
    maxLevel: 5,
    requires: ['house'],
    effects: [{ stat: 'cost:realm', kind: 'mul', amount: 0.95 }],
  },

  // Population growth.
  {
    id: 'well',
    world: 'realm',
    kind: 'building',
    name: 'Well',
    description: 'Clean water keeps families healthy, so the population grows faster.',
    baseCost: { stone: 30, wood: 10 },
    costGrowth: 1.8,
    maxLevel: 5,
    requires: ['hut'],
    effects: [{ stat: 'growth', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'tavern',
    world: 'realm',
    kind: 'building',
    name: 'Tavern',
    description: 'Word spreads about a good place to live, and settlers come.',
    baseCost: { planks: 40, food: 100 },
    costGrowth: 1.5,
    requires: ['house'],
    effects: [{ stat: 'growth', kind: 'add', amount: 0.02 }],
  },

  // Gateways to the other worlds.
  {
    id: 'library',
    world: 'realm',
    kind: 'building',
    name: 'Library',
    description: 'A place to study. The first one opens the Lab.',
    baseCost: { wood: 150, stone: 100 },
    costGrowth: 1.25,
    requires: ['workshop'],
    requiresBuildings: 10,
    unlocksWorld: 'lab',
    effects: [{ stat: 'rate:research', kind: 'add', amount: 0.5 }],
  },
  {
    id: 'shrine',
    world: 'realm',
    kind: 'building',
    name: 'Shrine',
    description: 'A quiet stone circle. The first one opens Arcana.',
    baseCost: { wood: 120, stone: 150 },
    costGrowth: 1.3,
    requires: ['workshop'],
    requiresBuildings: 10,
    unlocksWorld: 'arcana',
    effects: [{ stat: 'rate:mana', kind: 'add', amount: 0.3 }],
  },

  // Buildings that need science.
  {
    id: 'irrigation',
    world: 'realm',
    kind: 'building',
    name: 'Irrigation',
    description: 'Channels water to the fields. Needs Engineering from the Lab.',
    baseCost: { planks: 50, stone: 80 },
    costGrowth: 1.35,
    requires: ['farm', 'engineering'],
    effects: [{ stat: 'yield:food', kind: 'add', amount: 0.4 }],
  },
  {
    id: 'blastFurnace',
    world: 'realm',
    kind: 'building',
    name: 'Blast Furnace',
    description: 'Smelts Iron and Coal into Steel. Needs Metallurgy from the Lab.',
    baseCost: { bricks: 200, iron: 100 },
    costGrowth: 1.4,
    requires: ['coalMine', 'metallurgy'],
    upkeep: { iron: 1, coal: 0.5 },
    effects: [{ stat: 'rate:steel', kind: 'add', amount: 0.25 }],
  },
  {
    id: 'glassworks',
    world: 'realm',
    kind: 'building',
    name: 'Glassworks',
    description: 'Melts Stone into Glass over a coal fire. Needs Optics from the Lab.',
    baseCost: { bricks: 150, coal: 50 },
    costGrowth: 1.4,
    requires: ['kiln', 'coalMine', 'optics'],
    upkeep: { stone: 1, coal: 0.3 },
    effects: [{ stat: 'rate:glass', kind: 'add', amount: 0.2 }],
  },
  {
    id: 'goldMine',
    world: 'realm',
    kind: 'building',
    name: 'Gold Mine',
    description: 'Opens the Prospector job. Scholars run off to join the gold rush. Needs Geology from the Lab.',
    baseCost: { stone: 300, planks: 150 },
    costGrowth: 1.4,
    requires: ['mine', 'geology'],
    effects: [{ stat: 'yield:gold', kind: 'add', amount: 0.02 }],
  },
  {
    id: 'printingPress',
    world: 'realm',
    kind: 'building',
    name: 'Printing Press',
    description: 'Books for every scholar. Needs Printing from the Lab.',
    baseCost: { planks: 150, steel: 30 },
    costGrowth: 1.4,
    requires: ['printing'],
    effects: [{ stat: 'rate:research', kind: 'add', amount: 1 }],
  },
  {
    id: 'observatory',
    world: 'realm',
    kind: 'building',
    name: 'Observatory',
    description: 'Lenses on the sky help both scientists and mages. Needs Optics from the Lab.',
    baseCost: { glass: 40, bricks: 100 },
    costGrowth: 1.5,
    maxLevel: 10,
    requires: ['optics'],
    effects: [
      { stat: 'rate:research', kind: 'add', amount: 1.5 },
      { stat: 'rate:aether', kind: 'mul', amount: 1.05 },
    ],
  },
  {
    id: 'university',
    world: 'realm',
    kind: 'building',
    name: 'University',
    description: 'Science flourishes. Educated skeptics weaken magic. Needs Printing from the Lab.',
    baseCost: { bricks: 300, glass: 50, gold: 20 },
    costGrowth: 1.6,
    maxLevel: 10,
    requires: ['library', 'printing'],
    effects: [
      { stat: 'prod:lab', kind: 'mul', amount: 1.15 },
      { stat: 'rate:mana', kind: 'mul', amount: 0.95 },
    ],
  },

  // Buildings that need magic.
  {
    id: 'cathedral',
    world: 'realm',
    kind: 'building',
    name: 'Cathedral',
    description: 'Glass and gold raised to the heavens. Faith feeds magic, and dogma slows research.',
    baseCost: { bricks: 400, glass: 80, gold: 40 },
    costGrowth: 1.8,
    maxLevel: 5,
    requires: ['shrine', 'glassworks'],
    effects: [
      { stat: 'prod:arcana', kind: 'mul', amount: 1.2 },
      { stat: 'rate:research', kind: 'mul', amount: 0.95 },
    ],
  },
  {
    id: 'runesmith',
    world: 'realm',
    kind: 'building',
    name: 'Runesmith',
    description: 'Carves Essence into Stone to make Runestone. Needs Rune Lore from Arcana.',
    baseCost: { stone: 200, planks: 100 },
    costGrowth: 1.4,
    requires: ['runeLore'],
    upkeep: { stone: 1, essence: 0.1 },
    effects: [{ stat: 'rate:runestone', kind: 'add', amount: 0.05 }],
  },
  {
    id: 'leyAnchor',
    world: 'realm',
    kind: 'building',
    name: 'Ley Anchor',
    description: 'Runestones that calm the ley lines your mines disturb. Needs Rune Lore from Arcana.',
    baseCost: { runestone: 30, bricks: 100 },
    costGrowth: 2,
    maxLevel: 5,
    requires: ['runesmith'],
    effects: [{ stat: 'rate:mana', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'golemWorks',
    world: 'realm',
    kind: 'building',
    name: 'Golem Works',
    description:
      'Steel golems with rune hearts do the heavy lifting, and they draw on Mana. Needs Animation from Arcana and Automation from the Lab.',
    baseCost: { steel: 200, runestone: 50 },
    costGrowth: 1.8,
    maxLevel: 10,
    requires: ['blastFurnace', 'runesmith', 'animation', 'automation'],
    effects: [
      { stat: 'prod:realm', kind: 'mul', amount: 1.15 },
      { stat: 'rate:mana', kind: 'mul', amount: 0.93 },
    ],
  },

  // --------------------------------------------------------------- Arcana
  {
    id: 'manaWell',
    world: 'arcana',
    kind: 'building',
    name: 'Mana Well',
    description: 'Draws Mana up from below.',
    baseCost: { mana: 10 },
    costGrowth: 1.15,
    effects: [{ stat: 'rate:mana', kind: 'add', amount: 0.4 }],
  },
  {
    id: 'condenser',
    world: 'arcana',
    kind: 'building',
    name: 'Condenser',
    description: 'Presses Mana into Essence. Burns 1 Mana/s each.',
    baseCost: { mana: 50 },
    costGrowth: 1.2,
    requires: ['manaWell'],
    upkeep: { mana: 1 },
    effects: [{ stat: 'rate:essence', kind: 'add', amount: 0.1 }],
  },
  {
    id: 'focusCrystal',
    world: 'arcana',
    kind: 'building',
    name: 'Focus Crystal',
    description: 'Focuses the flow of Mana.',
    baseCost: { mana: 100, essence: 10 },
    costGrowth: 2.5,
    maxLevel: 10,
    requires: ['condenser'],
    effects: [
      { stat: 'rate:mana', kind: 'mul', amount: 1.25 },
      { stat: 'click:mana', kind: 'mul', amount: 1.5 },
    ],
  },
  {
    id: 'enchantedTools',
    world: 'arcana',
    kind: 'building',
    name: 'Enchanted Tools',
    description: 'Tools that work a little by themselves.',
    baseCost: { essence: 25 },
    costGrowth: 3,
    maxLevel: 5,
    requires: ['condenser'],
    effects: [{ stat: 'prod:realm', kind: 'mul', amount: 1.25 }],
  },
  {
    id: 'aetherRift',
    world: 'arcana',
    kind: 'building',
    name: 'Aether Rift',
    description: 'Tears reality open to let Aether through. Feeds on 0.5 Essence/s each, and the tear confuses instruments.',
    baseCost: { mana: 500, essence: 100 },
    costGrowth: 2,
    requires: ['condenser'],
    upkeep: { essence: 0.5 },
    effects: [
      { stat: 'rate:aether', kind: 'add', amount: 0.05 },
      { stat: 'rate:research', kind: 'mul', amount: 0.85 },
    ],
  },
  {
    id: 'aetherLens',
    world: 'arcana',
    kind: 'building',
    name: 'Aether Lens',
    description: 'Aether bends every spell into something stronger.',
    baseCost: { aether: 5 },
    costGrowth: 3,
    maxLevel: 5,
    requires: ['aetherRift'],
    effects: [{ stat: 'prod:arcana', kind: 'mul', amount: 1.5 }],
  },

  {
    id: 'summoningCircle',
    world: 'arcana',
    kind: 'building',
    name: 'Summon Demons',
    description: 'Demons pour power into Arcana, and they feed on the Realm\'s people.',
    baseCost: { mana: 300, essence: 30 },
    costGrowth: 1.6,
    requires: ['condenser'],
    effects: [
      { stat: 'prod:arcana', kind: 'mul', amount: 1.25 },
      { stat: 'deaths', kind: 'add', amount: 6 },
    ],
  },

  // Discoveries: one-time unlocks that Realm buildings can depend on.
  {
    id: 'fertilityRite',
    world: 'arcana',
    kind: 'tech',
    name: 'Fertility Rite',
    description: 'A blessing on the Realm\'s families.',
    baseCost: { mana: 150 },
    costGrowth: 1,
    requires: ['manaWell'],
    effects: [{ stat: 'growth', kind: 'mul', amount: 1.3 }],
  },
  {
    id: 'runeLore',
    world: 'arcana',
    kind: 'tech',
    name: 'Rune Lore',
    description: 'How to bind Essence into stone. Lets the Realm build a Runesmith.',
    baseCost: { mana: 200, essence: 20 },
    costGrowth: 1,
    requires: ['condenser'],
    effects: [{ stat: 'rate:essence', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'animation',
    world: 'arcana',
    kind: 'tech',
    name: 'Animation',
    description: 'Breathing motion into the lifeless. Lets the Realm build Golem Works.',
    baseCost: { essence: 100, aether: 20 },
    costGrowth: 1,
    requires: ['runeLore', 'aetherRift'],
    effects: [{ stat: 'prod:arcana', kind: 'mul', amount: 1.2 }],
  },

  // ------------------------------------------------------------------ Lab
  {
    id: 'scholar',
    world: 'lab',
    kind: 'building',
    name: 'Scholar',
    description: 'Produces Research.',
    baseCost: { research: 10 },
    costGrowth: 1.15,
    effects: [{ stat: 'rate:research', kind: 'add', amount: 0.3 }],
  },
  {
    id: 'laboratory',
    world: 'lab',
    kind: 'building',
    name: 'Laboratory',
    description: 'Iron equipment for serious experiments.',
    baseCost: { research: 60, iron: 20 },
    costGrowth: 1.25,
    requires: ['scholar'],
    effects: [{ stat: 'rate:research', kind: 'add', amount: 1.5 }],
  },
  {
    id: 'scientificMethod',
    world: 'lab',
    kind: 'tech',
    name: 'Scientific Method',
    description: 'Research is done properly now.',
    baseCost: { research: 50 },
    costGrowth: 1,
    effects: [{ stat: 'rate:research', kind: 'mul', amount: 1.25 }],
  },
  {
    id: 'engineering',
    world: 'lab',
    kind: 'tech',
    name: 'Engineering',
    description: 'Better planks and bricks. Lets the Realm build Irrigation.',
    baseCost: { research: 200, planks: 50 },
    costGrowth: 1,
    requires: ['scientificMethod'],
    effects: [
      { stat: 'rate:planks', kind: 'mul', amount: 1.25 },
      { stat: 'rate:bricks', kind: 'mul', amount: 1.25 },
    ],
  },
  {
    id: 'geology',
    world: 'lab',
    kind: 'tech',
    name: 'Geology',
    description: 'Knowing where to dig. Lets the Realm build a Gold Mine.',
    baseCost: { research: 250, stone: 100 },
    costGrowth: 1,
    requires: ['scientificMethod'],
    effects: [
      { stat: 'rate:stone', kind: 'mul', amount: 1.2 },
      { stat: 'yield:iron', kind: 'add', amount: 0.05 },
    ],
  },
  {
    id: 'optics',
    world: 'lab',
    kind: 'tech',
    name: 'Optics',
    description: 'Lenses and light. Lets the Realm build a Glassworks and an Observatory.',
    baseCost: { research: 500, bricks: 20 },
    costGrowth: 1,
    requires: ['engineering'],
    effects: [{ stat: 'prod:lab', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'printing',
    world: 'lab',
    kind: 'tech',
    name: 'Printing',
    description: 'Knowledge spreads. Lets the Realm build a Printing Press and a University.',
    baseCost: { research: 800, planks: 100 },
    costGrowth: 1,
    requires: ['optics'],
    effects: [{ stat: 'rate:research', kind: 'mul', amount: 1.2 }],
  },
  {
    id: 'medicine',
    world: 'lab',
    kind: 'tech',
    name: 'Medicine',
    description: 'Fewer people die young, so the Realm grows faster.',
    baseCost: { research: 300, food: 200 },
    costGrowth: 1,
    requires: ['scientificMethod'],
    effects: [{ stat: 'growth', kind: 'mul', amount: 1.5 }],
  },
  {
    id: 'metallurgy',
    world: 'lab',
    kind: 'tech',
    name: 'Metallurgy',
    description: 'Better smelting in the Realm. Lets the Realm build a Blast Furnace.',
    baseCost: { research: 150 },
    costGrowth: 1,
    requires: ['scientificMethod'],
    effects: [{ stat: 'rate:iron', kind: 'mul', amount: 1.5 }],
  },
  {
    id: 'rationalism',
    world: 'lab',
    kind: 'tech',
    name: 'Rationalism',
    description: 'Faster research. Widespread disbelief weakens magic.',
    baseCost: { research: 300 },
    costGrowth: 1,
    requires: ['scientificMethod'],
    effects: [
      { stat: 'rate:research', kind: 'mul', amount: 1.3 },
      { stat: 'rate:mana', kind: 'mul', amount: 0.8 },
    ],
  },
  {
    id: 'arcaneTheory',
    world: 'lab',
    kind: 'tech',
    name: 'Arcane Theory',
    description: 'Studying magic instead of dismissing it.',
    baseCost: { research: 400, essence: 30 },
    costGrowth: 1,
    requires: ['scientificMethod'],
    effects: [{ stat: 'rate:essence', kind: 'mul', amount: 1.3 }],
  },
  {
    id: 'industrialization',
    world: 'lab',
    kind: 'tech',
    name: 'Industrialization',
    description: 'Cheaper Realm buildings. The smog chokes Essence.',
    baseCost: { research: 600, iron: 100 },
    costGrowth: 1,
    requires: ['metallurgy'],
    effects: [
      { stat: 'cost:realm', kind: 'mul', amount: 0.85 },
      { stat: 'rate:essence', kind: 'mul', amount: 0.85 },
    ],
  },
  {
    id: 'automation',
    world: 'lab',
    kind: 'tech',
    name: 'Automation',
    description: 'Machines take over the Realm\'s busywork. Needed for Golem Works.',
    baseCost: { research: 1500, iron: 200 },
    costGrowth: 1,
    requires: ['industrialization'],
    effects: [{ stat: 'prod:realm', kind: 'mul', amount: 1.5 }],
  },
  {
    id: 'thaumicPhysics',
    world: 'lab',
    kind: 'tech',
    name: 'Thaumic Physics',
    description: 'Science and magic agree on something at last.',
    baseCost: { research: 2000, aether: 5 },
    costGrowth: 1,
    requires: ['rationalism', 'arcaneTheory'],
    effects: [
      { stat: 'rate:aether', kind: 'mul', amount: 2 },
      { stat: 'prod:lab', kind: 'mul', amount: 1.5 },
    ],
  },
];

export const NODES = Object.fromEntries(nodeList.map((n) => [n.id, n])) as Record<NodeId, NodeDef>;
export const NODE_ORDER: NodeId[] = nodeList.map((n) => n.id);

const metaList: MetaDef[] = [
  {
    id: 'headStartRealm',
    name: 'Head Start: Realm',
    description: 'Each Realm run starts with +2 Huts.',
    baseCost: 1,
    costGrowth: 2,
    maxLevel: 5,
  },
  {
    id: 'headStartArcana',
    name: 'Head Start: Arcana',
    description: 'Each Arcana run starts with +2 Mana Wells.',
    baseCost: 1,
    costGrowth: 2,
    maxLevel: 5,
  },
  {
    id: 'headStartLab',
    name: 'Head Start: Lab',
    description: 'Each Lab run starts with +2 Scholars.',
    baseCost: 1,
    costGrowth: 2,
    maxLevel: 5,
  },
  {
    id: 'resonanceRealm',
    name: 'Resonance: Realm',
    description: 'Realm production x1.1, permanently.',
    baseCost: 2,
    costGrowth: 1.6,
    effects: [{ stat: 'prod:realm', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'resonanceArcana',
    name: 'Resonance: Arcana',
    description: 'Arcana production x1.1, permanently.',
    baseCost: 2,
    costGrowth: 1.6,
    effects: [{ stat: 'prod:arcana', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'resonanceLab',
    name: 'Resonance: Lab',
    description: 'Lab production x1.1, permanently.',
    baseCost: 2,
    costGrowth: 1.6,
    effects: [{ stat: 'prod:lab', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'dampening',
    name: 'Dampening',
    description: 'Harmful effects between worlds are 10% weaker.',
    baseCost: 3,
    costGrowth: 2,
    maxLevel: 5,
  },
  {
    id: 'amplify',
    name: 'Amplify',
    description: 'Helpful effects between worlds are 10% stronger.',
    baseCost: 3,
    costGrowth: 2,
    maxLevel: 10,
  },
  {
    id: 'attunement',
    name: 'Echo Attunement',
    description: '+10% Echoes from every reset.',
    baseCost: 5,
    costGrowth: 2,
  },
  {
    id: 'retainedKnowledge',
    name: 'Retained Knowledge',
    description: 'Lab resets keep your most expensive tech (one more per level).',
    baseCost: 5,
    costGrowth: 3,
    maxLevel: 3,
  },
];

export const META = Object.fromEntries(metaList.map((m) => [m.id, m])) as Record<MetaId, MetaDef>;
export const META_ORDER: MetaId[] = metaList.map((m) => m.id);
