import type {
  AchievementDef,
  AchievementId,
  DepositDef,
  DepositId,
  JobDef,
  JobId,
  MetaDef,
  MetaId,
  NodeDef,
  NodeId,
  ResourceDef,
  ResourceId,
  WorldDef,
  WorldId,
} from './types';

export const WORLDS: Record<WorldId, WorldDef> = {
  realm: {
    id: 'realm',
    name: 'Realm',
    tagline: 'Feed your people, put them to work, and raise buildings.',
    unlockHint: 'Open from the start.',
    startsUnlocked: true,
    headStartNodes: ['hut'],
  },
  arcana: {
    id: 'arcana',
    name: 'Arcana',
    tagline: 'Draw on Mana and discover stranger magic.',
    unlockHint: 'Open the Lab and research Occultism, then build a Shrine in the Realm.',
    startsUnlocked: false,
    headStartNodes: ['manaWell'],
  },
  lab: {
    id: 'lab',
    name: 'Lab',
    tagline: 'Fund scholars and push the tech tree.',
    unlockHint: 'Build a Library in the Realm. It is made of Planks and Bricks, so it needs a Sawmill and a Kiln first.',
    startsUnlocked: false,
    headStartNodes: ['scholar'],
  },
};

export const WORLD_ORDER: WorldId[] = ['realm', 'arcana', 'lab'];

export const RESOURCES: Record<ResourceId, ResourceDef> = {
  wood: { id: 'wood', name: 'Wood', world: 'realm', value: 1, baseCap: 1000 },
  stone: { id: 'stone', name: 'Stone', world: 'realm', value: 1.5, baseCap: 1000 },
  food: { id: 'food', name: 'Food', world: 'realm', value: 1, baseCap: 1000 },
  clay: { id: 'clay', name: 'Clay', world: 'realm', value: 2, revealedBy: 'clayPit', baseCap: 500 },
  planks: { id: 'planks', name: 'Planks', world: 'realm', value: 4, revealedBy: 'sawmill', baseCap: 500 },
  bricks: { id: 'bricks', name: 'Bricks', world: 'realm', value: 5, revealedBy: 'kiln', baseCap: 500 },
  iron: { id: 'iron', name: 'Iron', world: 'realm', value: 6, revealedBy: 'mine', baseCap: 300 },
  coal: { id: 'coal', name: 'Coal', world: 'realm', value: 5, revealedBy: 'coalMine', baseCap: 300 },
  steel: { id: 'steel', name: 'Steel', world: 'realm', value: 25, revealedBy: 'blastFurnace', baseCap: 200 },
  glass: { id: 'glass', name: 'Glass', world: 'realm', value: 20, revealedBy: 'glassworks', baseCap: 150 },
  gold: { id: 'gold', name: 'Gold', world: 'realm', value: 60, revealedBy: 'goldMine', baseCap: 100 },
  runestone: { id: 'runestone', name: 'Runestone', world: 'realm', value: 80, revealedBy: 'runesmith', baseCap: 100 },
  mana: { id: 'mana', name: 'Mana', world: 'arcana', value: 1.5, baseCap: 300 },
  essence: { id: 'essence', name: 'Essence', world: 'arcana', value: 15, revealedBy: 'condenser' },
  fireEssence: { id: 'fireEssence', name: 'Fire Essence', world: 'arcana', value: 40, revealedBy: 'fireAltar' },
  lifeEssence: { id: 'lifeEssence', name: 'Life Essence', world: 'arcana', value: 40, revealedBy: 'lifeSpring' },
  shadowEssence: { id: 'shadowEssence', name: 'Shadow Essence', world: 'arcana', value: 60, revealedBy: 'shadowWell' },
  timeEssence: { id: 'timeEssence', name: 'Time Essence', world: 'arcana', value: 150, revealedBy: 'timeLoom' },
  aether: { id: 'aether', name: 'Aether', world: 'arcana', value: 120, revealedBy: 'aetherRift' },
  research: { id: 'research', name: 'Research', world: 'lab', value: 2 },
};

/** Base build time in seconds for each tier; each level already owned adds `BUILD_TIME_GROWTH`. */
export const TIER_SECONDS = { 1: 5, 2: 15, 3: 45, 4: 120, 5: 300, 6: 600 } as const;
export const BUILD_TIME_GROWTH = 1.05;

/** Realm population rules. */
/**
 * Wood, Stone, Clay and Coal are gathered from limited deposits. Only the forest regrows
 * on its own (really slowly); the rest can only be refilled by Arcana's earth magic.
 */
export const DEPOSITS: Record<DepositId, DepositDef> = {
  wood: { name: 'Forest', icon: '🌲', start: 8000, baseRegrow: 0.25, pollutionSlows: true },
  // Stone and Clay start empty: each Quarry or Clay Pit opens up more (see their size: effects).
  stone: { name: 'Stone quarries', icon: '🪨', start: 0, baseRegrow: 0 },
  clay: { name: 'Clay beds', icon: '🟫', start: 0, baseRegrow: 0 },
  coal: { name: 'Coal seams', icon: '⚫', start: 20000, baseRegrow: 0 },
};
export const DEPOSIT_ORDER = Object.keys(DEPOSITS) as DepositId[];
/** Share of what was gathered in a run that each Rich Earth level adds to a deposit's size on a Realm reset. */
export const DEPOSIT_GROWTH_PER_LEVEL = 0.01;

export const LAND = {
  /** Squares of land the Realm starts with; every building level takes one. */
  base: 20,
};

export const DEMONS = {
  /** Demons that answer the first summoning. */
  start: 1,
  /** The horde doubles this often, so demons arrive faster and faster. */
  doublingSeconds: 180,
  /** People left alive when the horde has eaten everyone else; then the spell ends. */
  survivors: 2,
};

export const POPULATION = {
  /** People at the start of every Realm run. */
  start: 2,
  /** Housing available before any Huts. */
  baseHousing: 3,
  /** People per second born or arriving while there is free housing, before `growth` modifiers (1 every 20s). */
  baseGrowth: 0.05,
  /** Food eaten to bring in each new person; nobody arrives while the stores are empty. */
  foodPerPerson: 10,
  /** Food each person eats per second. */
  foodPerSecond: 0.1,
  /** Food in the stores at the start of every Realm run, so nobody starves before the first Farmers are out. */
  startFood: 50,
  /** People who starve per second while nobody gets fed, before `starvation` modifiers (1 every 30s). */
  starvationRate: 1 / 30,
  /** Starvation never takes the last few, so the village can always recover. */
  starvationSurvivors: 2,
  /** Growth is divided by `1 + crowdingPenalty * crowding`, so each point of crowding slows it a little more. */
  crowdingPenalty: 0.02,
  /** Growth is also divided by `1 + pollutionPenalty * pollution`. */
  pollutionPenalty: 0.03,
};

// Every job has a small chance of killing its workers. Farming is safest, mining the most dangerous.
const jobList: JobDef[] = [
  {
    id: 'woodcutter',
    name: 'Woodcutters',
    resource: 'wood',
    baseYield: 0.5,
    accidentsPerHour: 0.1,
    accidentText: 'was crushed by a falling tree',
  },
  {
    id: 'stonecutter',
    name: 'Stonecutters',
    resource: 'stone',
    baseYield: 0.4,
    accidentsPerHour: 0.2,
    accidentText: 'was buried in a rockslide at the quarry',
    requires: ['quarry'],
  },
  {
    id: 'farmer',
    name: 'Farmers',
    resource: 'food',
    baseYield: 0.6,
    accidentsPerHour: 0.04,
    accidentText: 'was kicked by an ox',
  },
  {
    id: 'digger',
    name: 'Diggers',
    resource: 'clay',
    baseYield: 0.3,
    accidentsPerHour: 0.1,
    accidentText: 'drowned when a clay pit flooded',
    requires: ['clayPit'],
  },
  {
    id: 'miner',
    name: 'Miners',
    resource: 'iron',
    baseYield: 0.2,
    accidentsPerHour: 0.4,
    accidentText: 'died when a mine shaft collapsed',
    requires: ['mine'],
    // 2% per miner with one Mine, 1% more for each Mine after that.
    effects: [{ stat: 'rate:mana', kind: 'mul', amount: 0.98, scaleBy: { node: 'mine', perLevel: 0.5 } }],
  },
  {
    id: 'collier',
    name: 'Colliers',
    resource: 'coal',
    baseYield: 0.25,
    accidentsPerHour: 0.4,
    accidentText: 'was caught in a firedamp blast',
    requires: ['coalMine'],
    effects: [{ stat: 'rate:essence', kind: 'mul', amount: 0.99 }],
  },
  {
    id: 'prospector',
    name: 'Prospectors',
    resource: 'gold',
    baseYield: 0.05,
    accidentsPerHour: 0.2,
    accidentText: 'fell into a ravine while prospecting',
    requires: ['goldMine'],
    effects: [{ stat: 'rate:research', kind: 'mul', amount: 0.99 }],
  },
];

export const JOBS = Object.fromEntries(jobList.map((j) => [j.id, j])) as Record<JobId, JobDef>;
export const JOB_ORDER: JobId[] = jobList.map((j) => j.id);

export const RESOURCE_ORDER = Object.keys(RESOURCES) as ResourceId[];

const nodeList: NodeDef[] = [
  // ---------------------------------------------------------------- Realm
  // Basics: housing and raw materials.
  {
    id: 'hut',
    world: 'realm',
    kind: 'building',
    name: 'Hut',
    description: 'Room for more people to move in, though every home crowds the village a little.',
    baseCost: { wood: 10, food: 10 },
    costGrowth: 4,
    tier: 1,
    effects: [
      { stat: 'housing', kind: 'add', amount: 2 },
      { stat: 'crowding', kind: 'add', amount: 1 },
    ],
  },
  {
    id: 'warehouse',
    world: 'realm',
    kind: 'building',
    name: 'Warehouse',
    description:
      'Stores as much again of every Realm resource as you start with. Goods kept here slowly spoil, faster the more Warehouses you have. Needs Warehousing.',
    baseCost: { wood: 60, stone: 40 },
    costGrowth: 1.4,
    tier: 2,
    requires: ['warehousing'],
    effects: [
      { stat: 'storage:realm', kind: 'add', amount: 1 },
      { stat: 'decay:realm', kind: 'add', amount: 0.0002 },
    ],
  },
  {
    id: 'farm',
    world: 'realm',
    kind: 'building',
    name: 'Farm',
    description: 'Fields for your farmers. New people need Food to move in. Needs Agriculture from the Lab.',
    baseCost: { wood: 20 },
    costGrowth: 1.3,
    tier: 1,
    requires: ['agriculture'],
    effects: [{ stat: 'yield:food', kind: 'add', amount: 0.3 }],
  },
  {
    id: 'lumberCamp',
    world: 'realm',
    kind: 'building',
    name: 'Lumber Camp',
    description: 'Iron saws and sledges for your woodcutters. Needs Forestry from the Lab.',
    baseCost: { wood: 25, iron: 10 },
    costGrowth: 1.3,
    tier: 1,
    requires: ['forestry'],
    effects: [{ stat: 'yield:wood', kind: 'add', amount: 0.2 }],
  },
  {
    id: 'foresterLodge',
    world: 'realm',
    kind: 'building',
    name: 'Forester\'s Lodge',
    description: 'Foresters plant new trees, so the forest regrows faster.',
    baseCost: { wood: 50, stone: 30 },
    costGrowth: 1.5,
    tier: 2,
    maxLevel: 10,
    requires: ['lumberCamp'],
    effects: [{ stat: 'regrow:wood', kind: 'add', amount: 0.25 }],
  },
  {
    id: 'quarry',
    world: 'realm',
    kind: 'building',
    name: 'Quarry',
    description:
      'Opens the Stonecutter job. Each Quarry opens up 5,000 Stone to cut and makes stonecutters faster, but clears woodland: the forest holds 500 less Wood.',
    baseCost: { wood: 35 },
    costGrowth: 1.8,
    tier: 1,
    effects: [
      { stat: 'yield:stone', kind: 'add', amount: 0.15 },
      { stat: 'size:stone', kind: 'add', amount: 5000 },
      { stat: 'size:wood', kind: 'add', amount: -500 },
    ],
  },
  {
    id: 'clayPit',
    world: 'realm',
    kind: 'building',
    name: 'Clay Pit',
    description:
      'Opens the Digger job. Each pit opens up 3,000 Clay to dig and makes diggers faster, but the digging clears woodland: the forest holds 300 less Wood.',
    baseCost: { wood: 40, stone: 20 },
    costGrowth: 1.8,
    tier: 2,
    requires: ['quarry'],
    effects: [
      { stat: 'yield:clay', kind: 'add', amount: 0.1 },
      { stat: 'size:clay', kind: 'add', amount: 3000 },
      { stat: 'size:wood', kind: 'add', amount: -300 },
    ],
  },
  {
    id: 'workshop',
    world: 'realm',
    kind: 'building',
    name: 'Workshop',
    description: 'Better tools for every worker.',
    baseCost: { wood: 40, stone: 25 },
    costGrowth: 2.5,
    tier: 2,
    maxLevel: 10,
    requires: ['quarry'],
    effects: [
      { stat: 'rate:wood', kind: 'mul', amount: 1.15 },
      { stat: 'rate:stone', kind: 'mul', amount: 1.15 },
      { stat: 'rate:clay', kind: 'mul', amount: 1.15 },
      { stat: 'rate:iron', kind: 'mul', amount: 1.15 },
    ],
  },

  // Crafting: turning raw materials into better ones.
  {
    id: 'sawmill',
    world: 'realm',
    kind: 'building',
    name: 'Sawmill',
    description: 'Cuts Wood into Planks.',
    baseCost: { wood: 80, stone: 30 },
    costGrowth: 1.35,
    tier: 2,
    requires: ['workshop'],
    upkeep: { wood: 1 },
    effects: [{ stat: 'rate:planks', kind: 'add', amount: 0.1 }],
  },
  {
    id: 'kiln',
    world: 'realm',
    kind: 'building',
    name: 'Kiln',
    description: 'Fires Clay into Bricks, burning Wood. The smoke slows growth a little.',
    baseCost: { stone: 120, planks: 15 },
    costGrowth: 1.35,
    tier: 2,
    requires: ['clayPit', 'sawmill'],
    upkeep: { clay: 1, wood: 0.5 },
    effects: [{ stat: 'rate:bricks', kind: 'add', amount: 0.1 }, { stat: 'pollution', kind: 'add', amount: 1 }],
  },
  {
    id: 'house',
    world: 'realm',
    kind: 'building',
    name: 'House',
    description: 'Proper homes with room for a family. Packing people in slows growth. Needs Housing from the Lab.',
    baseCost: { planks: 30, bricks: 20 },
    costGrowth: 1.35,
    tier: 3,
    requires: ['sawmill', 'kiln', 'homebuilding'],
    effects: [
      { stat: 'housing', kind: 'add', amount: 5 },
      { stat: 'crowding', kind: 'add', amount: 2 },
    ],
  },
  {
    id: 'mine',
    world: 'realm',
    kind: 'building',
    name: 'Mine',
    description:
      'Opens the Miner job, and each Mine makes miners dig faster. Miners disturb the ley lines, and every Mine after the first makes each miner disturb them more. Needs Mining from the Lab.',
    baseCost: { wood: 60, stone: 80 },
    costGrowth: 1.35,
    tier: 2,
    requires: ['quarry', 'mining'],
    effects: [{ stat: 'yield:iron', kind: 'add', amount: 0.05 }],
  },
  {
    id: 'coalMine',
    world: 'realm',
    kind: 'building',
    name: 'Coal Mine',
    description: 'Opens the Collier job. Coal soot drifts into the magic and chokes the town.',
    baseCost: { planks: 60, stone: 100 },
    costGrowth: 1.35,
    tier: 3,
    requires: ['mine', 'sawmill'],
    effects: [{ stat: 'yield:coal', kind: 'add', amount: 0.05 }, { stat: 'pollution', kind: 'add', amount: 2 }],
  },
  {
    id: 'foundry',
    world: 'realm',
    kind: 'building',
    name: 'Foundry',
    description: 'Iron machinery speeds up the whole Realm, belching smoke.',
    baseCost: { bricks: 150, iron: 40 },
    costGrowth: 3,
    tier: 4,
    maxLevel: 10,
    requires: ['mine', 'kiln'],
    effects: [{ stat: 'prod:realm', kind: 'mul', amount: 1.2 }, { stat: 'pollution', kind: 'add', amount: 2 }],
  },
  {
    id: 'market',
    world: 'realm',
    kind: 'building',
    name: 'Market',
    description: 'Traders make every Realm building cheaper. Needs Currency from the Lab.',
    baseCost: { planks: 100, bricks: 60 },
    costGrowth: 1.8,
    tier: 3,
    maxLevel: 5,
    requires: ['house', 'currency'],
    effects: [{ stat: 'cost:realm', kind: 'mul', amount: 0.95 }],
  },

  {
    id: 'buildersGuild',
    world: 'realm',
    kind: 'building',
    name: "Builders' Guild",
    description: 'Master builders speed up every Realm construction.',
    baseCost: { planks: 60, bricks: 40 },
    costGrowth: 1.6,
    tier: 3,
    maxLevel: 10,
    requires: ['sawmill', 'kiln'],
    effects: [{ stat: 'speed:realm', kind: 'mul', amount: 1.15 }],
  },

  // Population growth.
  {
    id: 'well',
    world: 'realm',
    kind: 'building',
    name: 'Well',
    description: 'Clean water keeps families healthy: the population grows faster, fewer workers die, and the hungry last longer.',
    baseCost: { stone: 30, wood: 10 },
    costGrowth: 1.8,
    tier: 1,
    maxLevel: 5,
    requires: ['hut'],
    effects: [
      { stat: 'growth', kind: 'mul', amount: 1.1 },
      { stat: 'accidents', kind: 'mul', amount: 0.97 },
      { stat: 'starvation', kind: 'mul', amount: 0.8 },
    ],
  },
  {
    id: 'park',
    world: 'realm',
    kind: 'building',
    name: 'Park',
    description: 'Trees and green lawns clean the air, so pollution slows growth less. Needs Environmental Science from the Lab.',
    baseCost: { wood: 60, stone: 40, food: 40 },
    costGrowth: 1.6,
    tier: 2,
    maxLevel: 5,
    requires: ['well', 'environmentalScience'],
    effects: [{ stat: 'pollution', kind: 'mul', amount: 0.9 }],
  },
  {
    id: 'tavern',
    world: 'realm',
    kind: 'building',
    name: 'Tavern',
    description: 'Word spreads about a good place to live, and settlers come. The regulars are bad at paying, so the Tavern costs Gold to keep open.',
    baseCost: { planks: 40, food: 100 },
    costGrowth: 1.5,
    tier: 3,
    requires: ['house'],
    upkeep: { gold: 0.02 },
    effects: [{ stat: 'growth', kind: 'add', amount: 0.02 }],
  },

  // Gateways to the other worlds.
  {
    id: 'library',
    world: 'realm',
    kind: 'building',
    name: 'Library',
    description: 'A place to study, built from Planks and Bricks. The first one opens the Lab.',
    baseCost: { planks: 60, bricks: 40 },
    costGrowth: 1.25,
    tier: 3,
    requires: ['sawmill', 'kiln'],
    unlocksWorld: 'lab',
    effects: [{ stat: 'rate:research', kind: 'add', amount: 0.5 }],
  },
  {
    id: 'shrine',
    world: 'realm',
    kind: 'building',
    name: 'Shrine',
    description: 'A quiet stone circle. The first one opens Arcana. Needs Occultism from the Lab.',
    baseCost: { wood: 120, stone: 150 },
    costGrowth: 1.3,
    tier: 3,
    requires: ['workshop', 'occultism'],
    unlocksWorld: 'arcana',
    effects: [{ stat: 'rate:mana', kind: 'add', amount: 0.3 }],
  },

  // Buildings that need science.
  {
    id: 'irrigation',
    world: 'realm',
    kind: 'building',
    name: 'Irrigation',
    description: 'Channels water to the fields. Needs Engineering from the Lab.',
    baseCost: { planks: 50, stone: 80 },
    costGrowth: 1.35,
    tier: 4,
    requires: ['farm', 'engineering'],
    effects: [{ stat: 'yield:food', kind: 'add', amount: 0.4 }],
  },
  {
    id: 'aqueduct',
    world: 'realm',
    kind: 'building',
    name: 'Aqueduct',
    description: 'Fresh water for a crowded town, so crowding slows growth less. Needs Engineering from the Lab.',
    baseCost: { stone: 150, bricks: 60 },
    costGrowth: 1.6,
    tier: 4,
    maxLevel: 5,
    requires: ['well', 'engineering'],
    effects: [{ stat: 'crowding', kind: 'mul', amount: 0.85 }],
  },
  {
    id: 'blastFurnace',
    world: 'realm',
    kind: 'building',
    name: 'Blast Furnace',
    description: 'Smelts Iron and Coal into Steel. Needs Metallurgy from the Lab.',
    baseCost: { bricks: 200, iron: 100 },
    costGrowth: 1.4,
    tier: 4,
    requires: ['coalMine', 'metallurgy'],
    upkeep: { iron: 2.5, coal: 0.5 },
    effects: [{ stat: 'rate:steel', kind: 'add', amount: 0.25 }, { stat: 'pollution', kind: 'add', amount: 3 }],
  },
  {
    id: 'glassworks',
    world: 'realm',
    kind: 'building',
    name: 'Glassworks',
    description: 'Melts Stone into Glass over a coal fire. Needs Optics from the Lab.',
    baseCost: { bricks: 150, coal: 50 },
    costGrowth: 1.4,
    tier: 4,
    requires: ['kiln', 'coalMine', 'optics'],
    upkeep: { stone: 2, coal: 0.3 },
    effects: [{ stat: 'rate:glass', kind: 'add', amount: 0.2 }, { stat: 'pollution', kind: 'add', amount: 2 }],
  },
  {
    id: 'goldMine',
    world: 'realm',
    kind: 'building',
    name: 'Gold Mine',
    description: 'Opens the Prospector job. Scholars run off to join the gold rush. Needs Geology from the Lab.',
    baseCost: { stone: 300, planks: 150 },
    costGrowth: 1.4,
    tier: 4,
    requires: ['mine', 'geology'],
    effects: [{ stat: 'yield:gold', kind: 'add', amount: 0.02 }],
  },
  {
    id: 'printingPress',
    world: 'realm',
    kind: 'building',
    name: 'Printing Press',
    description: 'Books for every scholar, and printed doubt for every believer: it drains almost as much Mana as it adds Research. Needs Printing from the Lab.',
    baseCost: { planks: 150, steel: 30 },
    costGrowth: 1.4,
    tier: 4,
    requires: ['printing'],
    effects: [
      { stat: 'rate:research', kind: 'add', amount: 1 },
      { stat: 'rate:mana', kind: 'add', amount: -0.9 },
    ],
  },
  {
    id: 'church',
    world: 'realm',
    kind: 'building',
    name: 'Church',
    description: 'Stained glass and sermons: the opposite of a Printing Press. Faith feeds Mana, and doctrine holds back Research.',
    baseCost: { bricks: 120, glass: 40 },
    costGrowth: 1.4,
    tier: 4,
    requires: ['shrine'],
    effects: [
      { stat: 'rate:mana', kind: 'add', amount: 1 },
      { stat: 'rate:research', kind: 'add', amount: -0.9 },
    ],
  },
  {
    id: 'observatory',
    world: 'realm',
    kind: 'building',
    name: 'Observatory',
    description: 'Lenses on the sky help both scientists and mages. Needs Optics from the Lab.',
    baseCost: { glass: 40, bricks: 100 },
    costGrowth: 1.5,
    tier: 5,
    maxLevel: 10,
    requires: ['optics'],
    effects: [
      { stat: 'rate:research', kind: 'add', amount: 1.5 },
      { stat: 'rate:aether', kind: 'mul', amount: 1.05 },
    ],
  },
  {
    id: 'university',
    world: 'realm',
    kind: 'building',
    name: 'University',
    description: 'Science flourishes. Educated skeptics weaken magic. Needs Printing from the Lab.',
    baseCost: { bricks: 300, glass: 50, gold: 20 },
    costGrowth: 1.6,
    tier: 5,
    maxLevel: 10,
    requires: ['library', 'printing'],
    effects: [
      { stat: 'prod:lab', kind: 'mul', amount: 1.15 },
      { stat: 'rate:mana', kind: 'mul', amount: 0.95 },
    ],
  },

  // Buildings that need magic.
  {
    id: 'cathedral',
    world: 'realm',
    kind: 'building',
    name: 'Cathedral',
    description: 'Glass and gold raised to the heavens. Faith feeds magic, and dogma slows research.',
    baseCost: { bricks: 400, glass: 80, gold: 40 },
    costGrowth: 1.8,
    tier: 6,
    maxLevel: 5,
    requires: ['shrine', 'glassworks'],
    effects: [
      { stat: 'prod:arcana', kind: 'mul', amount: 1.2 },
      { stat: 'rate:research', kind: 'mul', amount: 0.95 },
    ],
  },
  {
    id: 'runesmith',
    world: 'realm',
    kind: 'building',
    name: 'Runesmith',
    description: 'Carves Essence into Stone to make Runestone. Needs Rune Lore from Arcana.',
    baseCost: { stone: 200, planks: 100 },
    costGrowth: 1.4,
    tier: 5,
    requires: ['runeLore'],
    upkeep: { stone: 1, essence: 0.1 },
    effects: [{ stat: 'rate:runestone', kind: 'add', amount: 0.05 }],
  },
  {
    id: 'leyAnchor',
    world: 'realm',
    kind: 'building',
    name: 'Ley Anchor',
    description: 'Runestones that calm the ley lines your mines disturb. Needs Rune Lore from Arcana.',
    baseCost: { runestone: 30, bricks: 100 },
    costGrowth: 2,
    tier: 5,
    maxLevel: 5,
    requires: ['runesmith'],
    effects: [{ stat: 'rate:mana', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'golemWorks',
    world: 'realm',
    kind: 'building',
    name: 'Golem Works',
    description:
      'Steel golems with rune hearts do the heavy lifting, and they draw on Mana. Needs Animation from Arcana and Automation from the Lab.',
    baseCost: { steel: 200, runestone: 50 },
    costGrowth: 1.8,
    tier: 6,
    maxLevel: 10,
    requires: ['blastFurnace', 'runesmith', 'animation', 'automation'],
    effects: [
      { stat: 'prod:realm', kind: 'mul', amount: 1.15 },
      { stat: 'speed:realm', kind: 'mul', amount: 1.1 },
      { stat: 'rate:mana', kind: 'mul', amount: 0.93 },
    ],
  },

  // --------------------------------------------------------------- Arcana
  {
    id: 'manaWell',
    world: 'arcana',
    kind: 'building',
    name: 'Mana Well',
    description: 'Draws Mana up from below.',
    baseCost: { mana: 10 },
    costGrowth: 1.15,
    tier: 1,
    effects: [{ stat: 'rate:mana', kind: 'add', amount: 0.4 }],
  },
  {
    id: 'manaCistern',
    world: 'arcana',
    kind: 'building',
    name: 'Mana Cistern',
    description: 'A stone basin that holds Mana instead of letting it seep away.',
    baseCost: { mana: 60 },
    costGrowth: 1.3,
    tier: 2,
    requires: ['manaWell'],
    effects: [{ stat: 'cap:mana', kind: 'add', amount: 250 }],
  },
  {
    id: 'leyVault',
    world: 'arcana',
    kind: 'building',
    name: 'Ley Vault',
    description: 'Folds space around the stored Mana, so every basin holds far more.',
    baseCost: { mana: 250, essence: 40 },
    costGrowth: 2.5,
    tier: 3,
    maxLevel: 5,
    requires: ['manaCistern', 'condenser'],
    effects: [{ stat: 'cap:mana', kind: 'mul', amount: 1.5 }],
  },
  {
    id: 'condenser',
    world: 'arcana',
    kind: 'building',
    name: 'Condenser',
    description: 'Presses Mana into Essence. Burns 1 Mana/s each.',
    baseCost: { mana: 50 },
    costGrowth: 1.2,
    tier: 2,
    requires: ['manaWell'],
    upkeep: { mana: 1 },
    effects: [{ stat: 'rate:essence', kind: 'add', amount: 0.1 }],
  },
  {
    id: 'focusCrystal',
    world: 'arcana',
    kind: 'building',
    name: 'Focus Crystal',
    description: 'Focuses the flow of Mana.',
    baseCost: { mana: 100, essence: 10 },
    costGrowth: 2.5,
    tier: 3,
    maxLevel: 10,
    requires: ['condenser'],
    effects: [{ stat: 'rate:mana', kind: 'mul', amount: 1.25 }],
  },
  {
    id: 'enchantedTools',
    world: 'arcana',
    kind: 'building',
    name: 'Enchanted Tools',
    description: 'Tools that work a little by themselves.',
    baseCost: { essence: 25 },
    costGrowth: 3,
    tier: 3,
    maxLevel: 5,
    requires: ['condenser'],
    effects: [{ stat: 'prod:realm', kind: 'mul', amount: 1.25 }],
  },
  {
    id: 'aetherRift',
    world: 'arcana',
    kind: 'building',
    name: 'Aether Rift',
    description: 'Tears reality open to let Aether through. Feeds on 0.5 Essence/s each, and the tear confuses instruments.',
    baseCost: { mana: 500, essence: 100 },
    costGrowth: 2,
    tier: 4,
    requires: ['condenser'],
    upkeep: { essence: 0.5 },
    effects: [
      { stat: 'rate:aether', kind: 'add', amount: 0.05 },
      { stat: 'rate:research', kind: 'mul', amount: 0.85 },
    ],
  },
  {
    id: 'aetherLens',
    world: 'arcana',
    kind: 'building',
    name: 'Aether Lens',
    description: 'Aether bends every spell into something stronger.',
    baseCost: { aether: 5 },
    costGrowth: 3,
    tier: 5,
    maxLevel: 5,
    requires: ['aetherRift'],
    effects: [{ stat: 'prod:arcana', kind: 'mul', amount: 1.5 }],
  },

  {
    id: 'summoningCircle',
    world: 'arcana',
    kind: 'tech',
    name: 'Summon Demons',
    description:
      'Spell with no way back: once cast it cannot be switched off. The horde doubles every 3 minutes, ' +
      'pouring power into Arcana while it eats the Realm\'s people. It only ends when 2 survivors are left.',
    baseCost: { mana: 300, essence: 30 },
    costGrowth: 1,
    tier: 3,
    requires: ['condenser'],
    spell: true,
    horde: true,
    effects: [
      { stat: 'prod:arcana', kind: 'mul', amount: 1.2, linear: true },
      { stat: 'deaths', kind: 'add', amount: 6 },
    ],
  },

  // Discoveries: one-time unlocks that Realm buildings can depend on.
  {
    id: 'fertilityRite',
    world: 'arcana',
    kind: 'tech',
    name: 'Fertility Rite',
    description: 'Spell: while it is on, the Realm\'s families grow faster.',
    baseCost: { mana: 150 },
    costGrowth: 1,
    tier: 2,
    requires: ['manaWell'],
    spell: true,
    upkeep: { mana: 1 },
    effects: [{ stat: 'growth', kind: 'mul', amount: 1.3 }],
  },
  {
    id: 'haste',
    world: 'arcana',
    kind: 'tech',
    name: 'Haste',
    description: 'Spell: while it is on, every builder in every world works faster.',
    baseCost: { mana: 400, essence: 40 },
    costGrowth: 1,
    tier: 3,
    requires: ['condenser'],
    spell: true,
    upkeep: { mana: 2, essence: 0.1 },
    effects: [
      { stat: 'speed:arcana', kind: 'mul', amount: 1.2 },
      { stat: 'speed:realm', kind: 'mul', amount: 1.2 },
      { stat: 'speed:lab', kind: 'mul', amount: 1.2 },
    ],
  },
  {
    id: 'runeLore',
    world: 'arcana',
    kind: 'tech',
    name: 'Rune Lore',
    description: 'How to bind Essence into stone. Lets the Realm build a Runesmith.',
    baseCost: { mana: 200, essence: 20 },
    costGrowth: 1,
    tier: 3,
    requires: ['condenser'],
    effects: [{ stat: 'rate:essence', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'geomancy',
    world: 'arcana',
    kind: 'tech',
    name: 'Geomancy',
    description: 'The magic of stone and soil. Lets you learn Earthsong.',
    baseCost: { mana: 400, essence: 60 },
    costGrowth: 1,
    tier: 3,
    requires: ['runeLore'],
    effects: [],
  },
  {
    id: 'animation',
    world: 'arcana',
    kind: 'tech',
    name: 'Animation',
    description: 'Spell: while it is on, Arcana itself stirs to work. Learning it lets the Realm build Golem Works.',
    baseCost: { essence: 100, aether: 20 },
    costGrowth: 1,
    tier: 5,
    requires: ['runeLore', 'aetherRift'],
    spell: true,
    upkeep: { essence: 1 },
    effects: [{ stat: 'prod:arcana', kind: 'mul', amount: 1.2 }],
  },

  // Essence schools: a discovery opens a new essence, a building distills it from
  // plain Essence, and that essence powers the school's spells.
  {
    id: 'pyromancy',
    world: 'arcana',
    kind: 'tech',
    name: 'Pyromancy',
    description: 'The study of fire. Lets you build a Fire Altar to make Fire Essence.',
    baseCost: { essence: 60, mana: 200 },
    costGrowth: 1,
    tier: 3,
    requires: ['condenser'],
    effects: [],
  },
  {
    id: 'fireAltar',
    world: 'arcana',
    kind: 'building',
    name: 'Fire Altar',
    description: 'Distills Essence into Fire Essence.',
    baseCost: { mana: 400, essence: 40 },
    costGrowth: 1.4,
    tier: 3,
    requires: ['pyromancy'],
    upkeep: { essence: 1 },
    effects: [{ stat: 'rate:fireEssence', kind: 'add', amount: 0.1 }],
  },
  {
    id: 'earthsong',
    world: 'arcana',
    kind: 'tech',
    name: 'Earthsong',
    description: 'Spell: sings stone and clay back into the Realm\'s quarries and clay beds.',
    baseCost: { essence: 80 },
    costGrowth: 1,
    tier: 3,
    requires: ['geomancy'],
    spell: true,
    upkeep: { essence: 0.5 },
    effects: [
      { stat: 'regrow:stone', kind: 'add', amount: 3 },
      { stat: 'regrow:clay', kind: 'add', amount: 2 },
    ],
  },
  {
    id: 'forgeFire',
    world: 'arcana',
    kind: 'tech',
    name: 'Forge Fire',
    description: 'Spell: magical flames in the Realm\'s furnaces and kilns.',
    baseCost: { fireEssence: 20 },
    costGrowth: 1,
    tier: 3,
    requires: ['fireAltar'],
    spell: true,
    upkeep: { fireEssence: 0.1 },
    effects: [
      { stat: 'rate:steel', kind: 'mul', amount: 1.5 },
      { stat: 'rate:bricks', kind: 'mul', amount: 1.3 },
      { stat: 'rate:glass', kind: 'mul', amount: 1.3 },
    ],
  },
  {
    id: 'vitalism',
    world: 'arcana',
    kind: 'tech',
    name: 'Vitalism',
    description: 'The study of life. Lets you build a Life Spring to make Life Essence.',
    baseCost: { essence: 60, mana: 200 },
    costGrowth: 1,
    tier: 3,
    requires: ['condenser'],
    effects: [],
  },
  {
    id: 'lifeSpring',
    world: 'arcana',
    kind: 'building',
    name: 'Life Spring',
    description: 'Distills Essence into Life Essence.',
    baseCost: { mana: 300, essence: 40 },
    costGrowth: 1.4,
    tier: 3,
    requires: ['vitalism'],
    upkeep: { essence: 1 },
    effects: [{ stat: 'rate:lifeEssence', kind: 'add', amount: 0.1 }],
  },
  {
    id: 'bountifulHarvest',
    world: 'arcana',
    kind: 'tech',
    name: 'Bountiful Harvest',
    description: 'Spell: the Realm\'s fields yield far more.',
    baseCost: { lifeEssence: 15 },
    costGrowth: 1,
    tier: 3,
    requires: ['lifeSpring'],
    spell: true,
    upkeep: { lifeEssence: 0.1 },
    effects: [{ stat: 'rate:food', kind: 'mul', amount: 1.5 }],
  },
  {
    id: 'healingLight',
    world: 'arcana',
    kind: 'tech',
    name: 'Healing Light',
    description: 'Spell: halves deaths in the Realm (even from demons) and helps families grow.',
    baseCost: { lifeEssence: 40 },
    costGrowth: 1,
    tier: 4,
    requires: ['lifeSpring'],
    spell: true,
    upkeep: { lifeEssence: 0.2 },
    effects: [
      { stat: 'deaths', kind: 'mul', amount: 0.5 },
      { stat: 'growth', kind: 'mul', amount: 1.2 },
    ],
  },
  {
    id: 'umbramancy',
    world: 'arcana',
    kind: 'tech',
    name: 'Umbramancy',
    description: 'What the demons taught you. Lets you build a Shadow Well to make Shadow Essence.',
    baseCost: { essence: 150 },
    costGrowth: 1,
    tier: 4,
    requires: ['summoningCircle'],
    effects: [],
  },
  {
    id: 'shadowWell',
    world: 'arcana',
    kind: 'building',
    name: 'Shadow Well',
    description: 'Distills Essence into Shadow Essence.',
    baseCost: { mana: 800, essence: 100 },
    costGrowth: 1.5,
    tier: 4,
    requires: ['umbramancy'],
    upkeep: { essence: 1 },
    effects: [{ stat: 'rate:shadowEssence', kind: 'add', amount: 0.1 }],
  },
  {
    id: 'shadowLabor',
    world: 'arcana',
    kind: 'tech',
    name: 'Shadow Labor',
    description: 'Spell: shades work the Realm through the night. Frightened families have fewer children.',
    baseCost: { shadowEssence: 30 },
    costGrowth: 1,
    tier: 4,
    requires: ['shadowWell'],
    spell: true,
    upkeep: { shadowEssence: 0.15 },
    effects: [
      { stat: 'prod:realm', kind: 'mul', amount: 1.3 },
      { stat: 'growth', kind: 'mul', amount: 0.7 },
    ],
  },
  {
    id: 'chronomancy',
    world: 'arcana',
    kind: 'tech',
    name: 'Chronomancy',
    description: 'Aether bends time. Lets you build a Time Loom to make Time Essence.',
    baseCost: { essence: 200, aether: 10 },
    costGrowth: 1,
    tier: 5,
    requires: ['aetherRift'],
    effects: [],
  },
  {
    id: 'timeLoom',
    world: 'arcana',
    kind: 'building',
    name: 'Time Loom',
    description: 'Weaves Essence and a thread of Aether into Time Essence.',
    baseCost: { essence: 300, aether: 20 },
    costGrowth: 1.6,
    tier: 5,
    requires: ['chronomancy'],
    upkeep: { essence: 1, aether: 0.02 },
    effects: [{ stat: 'rate:timeEssence', kind: 'add', amount: 0.05 }],
  },
  {
    id: 'timeWarp',
    world: 'arcana',
    kind: 'tech',
    name: 'Time Warp',
    description: 'Spell: construction in every world runs at a faster clock.',
    baseCost: { timeEssence: 20 },
    costGrowth: 1,
    tier: 5,
    requires: ['timeLoom'],
    spell: true,
    upkeep: { timeEssence: 0.05 },
    effects: [
      { stat: 'speed:realm', kind: 'mul', amount: 1.5 },
      { stat: 'speed:arcana', kind: 'mul', amount: 1.5 },
      { stat: 'speed:lab', kind: 'mul', amount: 1.5 },
    ],
  },
  {
    id: 'deepTime',
    world: 'arcana',
    kind: 'tech',
    name: 'Deep Time',
    description: 'Spell: aeons pass underground in moments, and the Realm\'s coal seams fill again.',
    baseCost: { timeEssence: 30, essence: 200 },
    costGrowth: 1,
    tier: 5,
    requires: ['timeLoom', 'geomancy'],
    spell: true,
    upkeep: { timeEssence: 0.05 },
    effects: [{ stat: 'regrow:coal', kind: 'add', amount: 2 }],
  },
  {
    id: 'quickenedMinds',
    world: 'arcana',
    kind: 'tech',
    name: 'Quickened Minds',
    description: 'Spell: scholars think faster than time allows.',
    baseCost: { timeEssence: 30 },
    costGrowth: 1,
    tier: 5,
    requires: ['timeLoom'],
    spell: true,
    upkeep: { timeEssence: 0.05 },
    effects: [{ stat: 'prod:lab', kind: 'mul', amount: 1.4 }],
  },

  // ------------------------------------------------------------------ Lab
  {
    id: 'scholar',
    world: 'lab',
    kind: 'building',
    name: 'Scholar',
    description: 'Produces Research. Each Scholar is an idle Realm person who moves into the Lab: paid for in Realm Food and still eating it, but taking no Realm housing or jobs. Demons hunt Scholars too.',
    baseCost: { food: 1000 },
    costGrowth: 1.5,
    tier: 1,
    upkeep: { food: 0.2 },
    people: 1,
    effects: [{ stat: 'rate:research', kind: 'add', amount: 0.3 }],
  },
  {
    id: 'laboratory',
    world: 'lab',
    kind: 'building',
    name: 'Laboratory',
    description: 'Iron equipment for serious experiments. Too much science is bad for magic: each Laboratory weakens all of Arcana a little.',
    baseCost: { planks: 30, iron: 20 },
    costGrowth: 1.25,
    tier: 2,
    requires: ['scholar'],
    effects: [
      { stat: 'rate:research', kind: 'add', amount: 1.5 },
      { stat: 'prod:arcana', kind: 'mul', amount: 0.97 },
    ],
  },
  {
    id: 'labAssistants',
    world: 'lab',
    kind: 'building',
    name: 'Lab Assistants',
    description: 'Extra hands make research go faster. They are hired with Realm Gold and, like Scholars, eat Realm Food but take no Realm housing or jobs.',
    baseCost: { gold: 25 },
    costGrowth: 1.6,
    tier: 2,
    maxLevel: 10,
    requires: ['scholar'],
    upkeep: { food: 0.2 },
    effects: [{ stat: 'rate:research', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'scientificMethod',
    world: 'lab',
    kind: 'tech',
    name: 'Scientific Method',
    description: 'Research is done properly now.',
    baseCost: { research: 50 },
    costGrowth: 1,
    tier: 1,
    effects: [{ stat: 'rate:research', kind: 'mul', amount: 1.25 }],
  },
  {
    id: 'engineering',
    world: 'lab',
    kind: 'tech',
    name: 'Engineering',
    description: 'Better planks and bricks. Lets the Realm build Irrigation and Aqueducts.',
    baseCost: { research: 200, planks: 50 },
    costGrowth: 1,
    tier: 2,
    requires: ['geology', 'metallurgy'],
    effects: [
      { stat: 'rate:planks', kind: 'mul', amount: 1.25 },
      { stat: 'rate:bricks', kind: 'mul', amount: 1.25 },
    ],
  },
  {
    id: 'warehousing',
    world: 'lab',
    kind: 'tech',
    name: 'Warehousing',
    description: 'Ledgers, crates and dry storerooms. Lets the Realm build Warehouses to store more of everything.',
    baseCost: { research: 150, wood: 100 },
    costGrowth: 1,
    tier: 2,
    requires: ['scientificMethod'],
    effects: [],
  },
  {
    id: 'mining',
    world: 'lab',
    kind: 'tech',
    name: 'Mining',
    description: 'Shafts, pit props and ore sorting. Lets the Realm dig Mines for Iron.',
    baseCost: { research: 120, stone: 60 },
    costGrowth: 1,
    tier: 2,
    requires: ['scientificMethod'],
    effects: [],
  },
  {
    id: 'geology',
    world: 'lab',
    kind: 'tech',
    name: 'Geology',
    description: 'Knowing where to dig. Lets the Realm build a Gold Mine.',
    baseCost: { research: 250, stone: 100 },
    costGrowth: 1,
    tier: 2,
    requires: ['mining'],
    effects: [
      { stat: 'rate:stone', kind: 'mul', amount: 1.2 },
      { stat: 'yield:iron', kind: 'add', amount: 0.05 },
    ],
  },
  {
    id: 'optics',
    world: 'lab',
    kind: 'tech',
    name: 'Optics',
    description: 'Lenses and light. Lets the Realm build a Glassworks and an Observatory.',
    baseCost: { research: 500, bricks: 20 },
    costGrowth: 1,
    tier: 3,
    requires: ['engineering'],
    effects: [{ stat: 'prod:lab', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'printing',
    world: 'lab',
    kind: 'tech',
    name: 'Printing',
    description: 'Knowledge spreads. Lets the Realm build a Printing Press and a University.',
    baseCost: { research: 800, planks: 100 },
    costGrowth: 1,
    tier: 4,
    requires: ['optics'],
    effects: [{ stat: 'rate:research', kind: 'mul', amount: 1.2 }],
  },
  {
    id: 'medicine',
    world: 'lab',
    kind: 'tech',
    name: 'Medicine',
    description: 'Fewer people die young in crowded homes, so crowding slows growth less, and injured workers are patched up.',
    baseCost: { research: 300, food: 200 },
    costGrowth: 1,
    tier: 2,
    requires: ['scientificMethod'],
    effects: [
      { stat: 'crowding', kind: 'mul', amount: 0.7 },
      { stat: 'accidents', kind: 'mul', amount: 0.7 },
    ],
  },
  {
    id: 'sanitation',
    world: 'lab',
    kind: 'tech',
    name: 'Sanitation',
    description: 'Sewers and clean streets. Crowding slows growth far less, and fewer workers die of infected wounds.',
    baseCost: { research: 900, bricks: 150 },
    costGrowth: 1,
    tier: 3,
    requires: ['medicine', 'engineering'],
    effects: [
      { stat: 'crowding', kind: 'mul', amount: 0.6 },
      { stat: 'accidents', kind: 'mul', amount: 0.8 },
    ],
  },
  {
    id: 'logistics',
    world: 'lab',
    kind: 'tech',
    name: 'Logistics',
    description: 'Planned supply lines make Realm construction much faster.',
    baseCost: { research: 400, planks: 100 },
    costGrowth: 1,
    tier: 3,
    requires: ['engineering'],
    effects: [{ stat: 'speed:realm', kind: 'mul', amount: 1.3 }],
  },
  {
    id: 'metallurgy',
    world: 'lab',
    kind: 'tech',
    name: 'Metallurgy',
    description: 'Better smelting in the Realm. Lets the Realm build a Blast Furnace.',
    baseCost: { research: 150 },
    costGrowth: 1,
    tier: 2,
    requires: ['scientificMethod'],
    effects: [{ stat: 'rate:iron', kind: 'mul', amount: 1.5 }],
  },
  {
    id: 'rationalism',
    world: 'lab',
    kind: 'tech',
    name: 'Rationalism',
    description: 'Faster research. Widespread disbelief weakens magic. Repeatable.',
    baseCost: { research: 300 },
    costGrowth: 1.6,
    tier: 3,
    maxLevel: 10,
    requires: ['scientificMethod'],
    effects: [
      { stat: 'rate:research', kind: 'mul', amount: 1.3 },
      { stat: 'rate:mana', kind: 'mul', amount: 0.8 },
    ],
  },
  {
    id: 'settlements',
    world: 'lab',
    kind: 'tech',
    name: 'Settlements',
    description: 'How villages grow into towns. The root of Agriculture, Housing and Currency, and newcomers settle in a little faster.',
    baseCost: { research: 50 },
    costGrowth: 1,
    tier: 1,
    effects: [{ stat: 'growth', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'homebuilding',
    world: 'lab',
    kind: 'tech',
    name: 'Housing',
    description: 'Timber frames and brick walls: lets the Realm build Houses, laid out so they crowd the village a little less.',
    baseCost: { research: 150 },
    costGrowth: 1,
    tier: 2,
    requires: ['settlements'],
    effects: [{ stat: 'crowding', kind: 'mul', amount: 0.9 }],
  },
  {
    id: 'agriculture',
    world: 'lab',
    kind: 'tech',
    name: 'Agriculture',
    description: 'Crop rotation and ploughs. Lets the Realm lay out Farms, and every field yields twice as much.',
    baseCost: { research: 100 },
    costGrowth: 1,
    tier: 1,
    requires: ['settlements'],
    effects: [{ stat: 'rate:food', kind: 'mul', amount: 2 }],
  },
  {
    id: 'currency',
    world: 'lab',
    kind: 'tech',
    name: 'Currency',
    description: 'Minted coins instead of barter. Lets the Realm build Markets, and makes Gold worth digging for.',
    baseCost: { research: 200 },
    costGrowth: 1,
    tier: 2,
    requires: ['settlements'],
    effects: [{ stat: 'rate:gold', kind: 'mul', amount: 1.15 }],
  },
  {
    id: 'occultism',
    world: 'lab',
    kind: 'tech',
    name: 'Occultism',
    description: 'Candles, old books and whispered rites. Lets the Realm raise a Shrine, which opens Arcana, and leads to Arcane Theory.',
    baseCost: { research: 10000 },
    costGrowth: 1,
    tier: 4,
    effects: [{ stat: 'rate:mana', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'arcaneTheory',
    world: 'lab',
    kind: 'tech',
    name: 'Arcane Theory',
    description: 'Studying magic instead of dismissing it.',
    baseCost: { research: 400, essence: 30 },
    costGrowth: 1,
    tier: 3,
    requires: ['occultism'],
    effects: [{ stat: 'rate:essence', kind: 'mul', amount: 1.3 }],
  },
  {
    id: 'industrialization',
    world: 'lab',
    kind: 'tech',
    name: 'Industrialization',
    description: 'Cheaper Realm buildings. The smog chokes Essence and the Realm\'s growth.',
    baseCost: { research: 600, iron: 100 },
    costGrowth: 1,
    tier: 4,
    requires: ['metallurgy'],
    effects: [
      { stat: 'cost:realm', kind: 'mul', amount: 0.85 },
      { stat: 'rate:essence', kind: 'mul', amount: 0.85 },
      { stat: 'pollution', kind: 'add', amount: 8 },
    ],
  },
  {
    id: 'cartography',
    world: 'lab',
    kind: 'tech',
    name: 'Cartography',
    description: 'Map the lands around the Realm: 1 more square of land to build on, kept through Lab resets. Repeatable up to 10 times, each costing twice as much. Leads to Sailing.',
    baseCost: { research: 120 },
    costGrowth: 2,
    tier: 2,
    maxLevel: 10,
    requires: ['scientificMethod'],
    permanent: true,
    effects: [{ stat: 'land', kind: 'add', amount: 1 }],
  },
  {
    id: 'sailing',
    world: 'lab',
    kind: 'tech',
    name: 'Sailing',
    description: 'Boats built from Planks. Fishing boats bring in more Food, and the coast opens up to explorers.',
    baseCost: { research: 500, planks: 150 },
    costGrowth: 1,
    tier: 3,
    requires: ['cartography', 'engineering'],
    effects: [{ stat: 'rate:food', kind: 'mul', amount: 1.15 }],
  },
  {
    id: 'navigation',
    world: 'lab',
    kind: 'tech',
    name: 'Navigation',
    description: 'Charts, lenses and the stars: ships can cross open sea. Trade brings in more Gold, and Expeditions can set out.',
    baseCost: { research: 1000, glass: 20 },
    costGrowth: 1,
    tier: 4,
    requires: ['sailing', 'optics'],
    effects: [{ stat: 'rate:gold', kind: 'mul', amount: 1.25 }],
  },
  {
    id: 'expedition',
    world: 'lab',
    kind: 'tech',
    name: 'Expedition',
    description: 'Sail beyond the maps. Each expedition finds 5 more squares of land for the Realm, kept through Lab resets. Repeatable. Needs Navigation.',
    baseCost: { research: 1000, food: 500 },
    costGrowth: 1.3,
    tier: 4,
    maxLevel: 30,
    requires: ['navigation'],
    permanent: true,
    effects: [{ stat: 'land', kind: 'add', amount: 5 }],
  },
  {
    id: 'forestry',
    world: 'lab',
    kind: 'tech',
    name: 'Forestry',
    description: 'Managed woodland: the Realm\'s forest regrows twice as fast.',
    baseCost: { research: 250, wood: 200 },
    costGrowth: 1,
    tier: 2,
    requires: ['scientificMethod'],
    effects: [{ stat: 'regrow:wood', kind: 'mul', amount: 2 }],
  },
  {
    id: 'environmentalScience',
    world: 'lab',
    kind: 'tech',
    name: 'Environmental Science',
    description: 'Understanding how the land heals: faster regrowth, less pollution, and the Realm can plant Parks.',
    baseCost: { research: 1200, glass: 40 },
    costGrowth: 1,
    tier: 5,
    requires: ['forestry', 'filtration'],
    effects: [
      { stat: 'regrow:wood', kind: 'mul', amount: 2 },
      { stat: 'pollution', kind: 'mul', amount: 0.8 },
    ],
  },
  {
    id: 'filtration',
    world: 'lab',
    kind: 'tech',
    name: 'Filtration',
    description: 'Filters on every chimney. Pollution slows the Realm\'s growth far less.',
    baseCost: { research: 800, iron: 80 },
    costGrowth: 1,
    tier: 4,
    requires: ['metallurgy', 'medicine'],
    effects: [{ stat: 'pollution', kind: 'mul', amount: 0.5 }],
  },
  {
    id: 'automation',
    world: 'lab',
    kind: 'tech',
    name: 'Automation',
    description: 'Machines take over the Realm\'s busywork. Needed for Golem Works.',
    baseCost: { research: 1500, iron: 200 },
    costGrowth: 1,
    tier: 5,
    requires: ['industrialization'],
    effects: [{ stat: 'prod:realm', kind: 'mul', amount: 1.5 }],
  },
  {
    id: 'thaumicPhysics',
    world: 'lab',
    kind: 'tech',
    name: 'Thaumic Physics',
    description: 'Science and magic agree on something at last.',
    baseCost: { research: 2000, aether: 5 },
    costGrowth: 1,
    tier: 6,
    requires: ['rationalism', 'arcaneTheory'],
    effects: [
      { stat: 'rate:aether', kind: 'mul', amount: 2 },
      { stat: 'prod:lab', kind: 'mul', amount: 1.5 },
    ],
  },
];

export const NODES = Object.fromEntries(nodeList.map((n) => [n.id, n])) as Record<NodeId, NodeDef>;
export const NODE_ORDER: NodeId[] = nodeList.map((n) => n.id);

const metaList: MetaDef[] = [
  {
    id: 'headStartRealm',
    name: 'Head Start: Realm',
    description: 'Each Realm run starts with +2 Huts.',
    baseCost: 1,
    costGrowth: 2,
    maxLevel: 5,
  },
  {
    id: 'headStartArcana',
    name: 'Head Start: Arcana',
    description: 'Each Arcana run starts with +2 Mana Wells.',
    baseCost: 1,
    costGrowth: 2,
    maxLevel: 5,
  },
  {
    id: 'headStartLab',
    name: 'Head Start: Lab',
    description: 'Each Lab run starts with +2 Scholars.',
    baseCost: 1,
    costGrowth: 2,
    maxLevel: 5,
  },
  {
    id: 'resonanceRealm',
    name: 'Resonance: Realm',
    description: 'Realm production x1.1, permanently.',
    baseCost: 2,
    costGrowth: 1.6,
    effects: [{ stat: 'prod:realm', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'resonanceArcana',
    name: 'Resonance: Arcana',
    description: 'Arcana production x1.1, permanently.',
    baseCost: 2,
    costGrowth: 1.6,
    effects: [{ stat: 'prod:arcana', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'resonanceLab',
    name: 'Resonance: Lab',
    description: 'Lab production x1.1, permanently.',
    baseCost: 2,
    costGrowth: 1.6,
    effects: [{ stat: 'prod:lab', kind: 'mul', amount: 1.1 }],
  },
  {
    id: 'dampening',
    name: 'Dampening',
    description: 'Harmful effects between worlds are 10% weaker.',
    baseCost: 3,
    costGrowth: 2,
    maxLevel: 5,
  },
  {
    id: 'amplify',
    name: 'Amplify',
    description: 'Helpful effects between worlds are 10% stronger.',
    baseCost: 3,
    costGrowth: 2,
    maxLevel: 10,
  },
  {
    id: 'attunement',
    name: 'Echo Attunement',
    description: '+10% Echoes from every reset.',
    baseCost: 5,
    costGrowth: 2,
  },
  {
    id: 'swiftHands',
    name: 'Swift Hands',
    description: 'Everything builds 10% faster, in every world.',
    baseCost: 2,
    costGrowth: 1.8,
    effects: [
      { stat: 'speed:realm', kind: 'mul', amount: 1.1 },
      { stat: 'speed:arcana', kind: 'mul', amount: 1.1 },
      { stat: 'speed:lab', kind: 'mul', amount: 1.1 },
    ],
  },
  {
    id: 'masterBuilders',
    name: 'Master Builders',
    description: 'Each world can work on one more building, discovery or tech at the same time (up to 5).',
    baseCost: 3,
    costGrowth: 2,
    maxLevel: 4,
  },
  {
    id: 'richEarth',
    name: 'Rich Earth',
    description: 'On a Realm reset, every deposit grows by 1% of what was gathered from it that run, per level.',
    baseCost: 1,
    costGrowth: 1.12,
    maxLevel: 50,
  },
  {
    id: 'multicast',
    name: 'Multicast',
    description: 'Keep one more Arcana spell on at the same time.',
    baseCost: 25,
    costGrowth: 4,
    maxLevel: 3,
  },
  {
    id: 'retainedKnowledge',
    name: 'Retained Knowledge',
    description: 'Lab resets keep your most expensive tech (one more per level).',
    baseCost: 5,
    costGrowth: 3,
    maxLevel: 3,
  },
];

export const META = Object.fromEntries(metaList.map((m) => [m.id, m])) as Record<MetaId, MetaDef>;
export const META_ORDER: MetaId[] = metaList.map((m) => m.id);

// ------------------------------------------------------------ achievements

const achievementList: AchievementDef[] = [
  {
    id: 'village',
    name: 'A Proper Village',
    goal: 'Have 10 people in the Realm at once.',
    reward: 'Every Realm run starts with 2 more people.',
    progress: (state) => [Math.floor(state.population), 10],
    startPeople: 2,
  },
  {
    id: 'deforested',
    name: 'I Can\'t See the Forest or All the Trees',
    goal: 'Clear the whole forest away with Quarries and Clay Pits, so it cannot hold a single tree.',
    reward: 'The forest is 2,000 Wood bigger, and every Realm run starts with it full.',
    progress: (state, mods) => {
      // How much the buildings have cleared, against the forest there was to clear.
      const cleared = nodeList.reduce((sum, n) => {
        const cut = n.effects.find((e) => e.stat === 'size:wood' && e.kind === 'add' && e.amount < 0);
        return cut ? sum - cut.amount * state.nodes[n.id] : sum;
      }, 0);
      const left = Math.max(0, state.deposits.wood.max + (mods.get('size:wood')?.add ?? 0));
      return [cleared, cleared + left];
    },
    effects: [{ stat: 'size:wood', kind: 'add', amount: 2000 }],
  },
];

export const ACHIEVEMENTS = Object.fromEntries(achievementList.map((a) => [a.id, a])) as Record<AchievementId, AchievementDef>;
export const ACHIEVEMENT_ORDER: AchievementId[] = achievementList.map((a) => a.id);
